# Generated by Django 5.2.17 on 2026-09-02 00:57
# ruff: noqa: E501

import django.db.models.deletion
import django.db.models.lookups
from django.db import migrations, models

SEEDED_FACTS = (
    ("citizenship", "enum", ["egyptian", "other"], None, False),
    ("application_location", "enum", ["inside_egypt", "outside_egypt"], None, False),
    (
        "existing_passport_state",
        "enum",
        ["expired", "pages_full", "valid_with_pages", "lost", "damaged", "none"],
        None,
        False,
    ),
    ("passport_class", "enum", ["ordinary", "other"], None, False),
    ("birth_date", "date", [], None, False),
    ("sex", "enum", ["male", "female"], None, False),
    (
        "national_id_status",
        "enum",
        ["valid_current_data", "invalid_or_expired", "not_held"],
        None,
        False,
    ),
    ("is_student", "boolean", [], None, False),
    ("has_current_enrollment_certificate", "boolean", [], None, False),
    ("has_military_status_document", "boolean", [], None, False),
    ("has_required_photos", "boolean", [], None, False),
    ("service_level", "enum", ["standard", "urgent", "premium"], None, False),
    ("residence_police_jurisdiction", "string", [], None, False),
    (
        "minor_presenting_adult_role",
        "enum",
        ["parent", "legal_guardian", "other", "unknown"],
        None,
        False,
    ),
    ("national_id_possession_state", "enum", ["held", "lost", "damaged", "none"], None, False),
    ("national_id_expiry_date", "date", [], None, False),
    (
        "national_id_data_change_kind",
        "enum",
        ["none", "residence", "profession", "marital_status", "other", "multiple"],
        None,
        False,
    ),
    ("residence_governorate", "string", [], None, False),
    ("residence_district", "string", [], None, False),
    ("father_alive", "boolean", [], None, False),
    ("other_living_sons_of_father_count", "integer", [], 0, False),
    (
        "father_unable_to_earn_status",
        "enum",
        ["authority_documented_unable", "not_documented_unable"],
        None,
        False,
    ),
    (
        "other_capable_family_support_for_father",
        "enum",
        ["none_known", "present", "unknown"],
        None,
        False,
    ),
    (
        "mother_family_status",
        "enum",
        ["widowed", "irrevocably_divorced", "husband_authority_documented_unable", "other"],
        None,
        False,
    ),
    (
        "other_capable_family_support_for_mother",
        "enum",
        ["none_known", "present", "unknown"],
        None,
        False,
    ),
    ("unmarried_sisters_requiring_support_count", "integer", [], 0, False),
    (
        "other_capable_family_support_for_sisters",
        "enum",
        ["none_known", "present", "unknown"],
        None,
        False,
    ),
    (
        "missing_relative_category",
        "enum",
        ["officer", "volunteer", "conscript", "citizen", "none"],
        None,
        False,
    ),
    (
        "missing_relative_cause",
        "enum",
        ["war_operations", "terrorist_operations", "other"],
        None,
        False,
    ),
    (
        "missing_relative_alive_status",
        "enum",
        ["missing", "returned_or_proven_alive", "unknown"],
        None,
        False,
    ),
    (
        "applicant_largest_eligible_relative_status",
        "enum",
        ["authority_documented_yes", "authority_documented_no"],
        None,
        False,
    ),
    (
        "sibling_service_status",
        "enum",
        ["compulsory_service", "reserve_recall", "none"],
        None,
        False,
    ),
    (
        "applicant_eldest_remaining_brother_status",
        "enum",
        ["authority_documented_yes", "authority_documented_no"],
        None,
        False,
    ),
    (
        "article7_third_exclusion_status",
        "enum",
        ["none_documented", "exclusion_present", "unknown"],
        None,
        False,
    ),
    ("age_years_on_evaluation_date", "integer", [], 0, True),
    ("card_expired_before_evaluation_date", "boolean", [], None, True),
    ("renewal_deadline_date", "date", [], None, True),
    ("renewal_deadline_passed", "boolean", [], None, True),
    ("only_son_candidate", "boolean", [], None, True),
)


def seed_facts(apps, schema_editor):
    FactDefinition = apps.get_model("knowledge", "FactDefinition")
    FactDefinition.objects.bulk_create(
        FactDefinition(
            key=key,
            kind=kind,
            enum_values=enum_values,
            minimum=minimum,
            derived=derived,
            is_published=True,
        )
        for key, kind, enum_values, minimum, derived in SEEDED_FACTS
    )


def unseed_facts(apps, schema_editor):
    FactDefinition = apps.get_model("knowledge", "FactDefinition")
    FactDefinition.objects.filter(key__in=[row[0] for row in SEEDED_FACTS]).delete()


PUBLISHED_FACT_TRIGGER_SQL = """
CREATE FUNCTION knowledge_protect_published_fact() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'DELETE' AND OLD.is_published THEN
        RAISE EXCEPTION 'published Fact definitions cannot be deleted';
    END IF;
    IF TG_OP = 'UPDATE' AND OLD.is_published AND (
        NEW.key IS DISTINCT FROM OLD.key OR
        NEW.kind IS DISTINCT FROM OLD.kind OR
        NEW.enum_values IS DISTINCT FROM OLD.enum_values OR
        NEW.minimum IS DISTINCT FROM OLD.minimum OR
        NEW.derived IS DISTINCT FROM OLD.derived OR
        NEW.is_published IS DISTINCT FROM OLD.is_published
    ) THEN
        RAISE EXCEPTION 'published Fact definitions are immutable';
    END IF;
    RETURN CASE WHEN TG_OP = 'DELETE' THEN OLD ELSE NEW END;
END;
$$ LANGUAGE plpgsql;
CREATE TRIGGER knowledge_published_fact_guard
BEFORE UPDATE OR DELETE ON knowledge_factdefinition
FOR EACH ROW EXECUTE FUNCTION knowledge_protect_published_fact();
"""

PUBLISHED_FACT_TRIGGER_REVERSE_SQL = """
DROP TRIGGER IF EXISTS knowledge_published_fact_guard ON knowledge_factdefinition;
DROP FUNCTION IF EXISTS knowledge_protect_published_fact();
"""


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FactDefinition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("key", models.CharField(max_length=128, unique=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("boolean", "Boolean"),
                            ("enum", "Enum"),
                            ("integer", "Integer"),
                            ("date", "Date"),
                            ("string", "String"),
                        ],
                        max_length=16,
                    ),
                ),
                ("enum_values", models.JSONField(blank=True, default=list)),
                ("minimum", models.IntegerField(blank=True, null=True)),
                ("derived", models.BooleanField(default=False)),
                ("is_published", models.BooleanField(default=False, editable=False)),
            ],
            options={
                "ordering": ("key",),
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("key__regex", ".*[^[:space:]].*")),
                        name="fact_key_nonblank",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("kind__in", ["boolean", "enum", "integer", "date", "string"])
                        ),
                        name="fact_kind_supported",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("minimum__isnull", True), ("minimum__gte", 0), _connector="OR"
                        ),
                        name="fact_minimum_nonnegative",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("kind", "integer"), ("minimum__isnull", True), _connector="OR"
                        ),
                        name="fact_minimum_integer_only",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("kind", "enum"), models.Q(("enum_values", []), _negated=True)
                            ),
                            models.Q(
                                models.Q(("kind", "enum"), _negated=True), ("enum_values", [])
                            ),
                            _connector="OR",
                        ),
                        name="fact_enum_vocabulary",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("semantic_id", models.CharField(max_length=128, unique=True)),
                ("text_ar", models.TextField()),
                ("text_en", models.TextField()),
            ],
            options={
                "ordering": ("semantic_id",),
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("semantic_id__regex", ".*[^[:space:]].*")),
                        name="service_id_nonblank",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("text_ar__regex", ".*[^[:space:]].*")),
                        name="service_ar_nonblank",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("text_en__regex", ".*[^[:space:]].*")),
                        name="service_en_nonblank",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ServiceContradiction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("semantic_id", models.CharField(max_length=128, unique=True)),
                ("condition", models.JSONField()),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contradictions",
                        to="knowledge.service",
                    ),
                ),
            ],
            options={
                "ordering": ("service_id", "semantic_id"),
            },
        ),
        migrations.CreateModel(
            name="ServiceContradictionFact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("position", models.PositiveIntegerField()),
                (
                    "contradiction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fact_links",
                        to="knowledge.servicecontradiction",
                    ),
                ),
                (
                    "fact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="contradiction_links",
                        to="knowledge.factdefinition",
                    ),
                ),
            ],
            options={
                "ordering": ("position", "fact__key"),
            },
        ),
        migrations.AddField(
            model_name="servicecontradiction",
            name="facts",
            field=models.ManyToManyField(
                related_name="contradictions",
                through="knowledge.ServiceContradictionFact",
                to="knowledge.factdefinition",
            ),
        ),
        migrations.CreateModel(
            name="ServiceQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("semantic_id", models.CharField(max_length=128, unique=True)),
                ("text_ar", models.TextField()),
                ("text_en", models.TextField()),
                ("priority", models.PositiveIntegerField()),
                (
                    "fact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="primary_questions",
                        to="knowledge.factdefinition",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="knowledge.service",
                    ),
                ),
            ],
            options={
                "ordering": ("service_id", "priority", "semantic_id"),
            },
        ),
        migrations.CreateModel(
            name="ServiceQuestionResolvedFact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("position", models.PositiveIntegerField()),
                (
                    "fact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="question_resolution_links",
                        to="knowledge.factdefinition",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resolved_fact_links",
                        to="knowledge.servicequestion",
                    ),
                ),
            ],
            options={
                "ordering": ("position", "fact__key"),
            },
        ),
        migrations.AddField(
            model_name="servicequestion",
            name="resolves_facts",
            field=models.ManyToManyField(
                related_name="resolving_questions",
                through="knowledge.ServiceQuestionResolvedFact",
                to="knowledge.factdefinition",
            ),
        ),
        migrations.CreateModel(
            name="Procedure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("semantic_id", models.CharField(max_length=128, unique=True)),
                ("text_ar", models.TextField()),
                ("text_en", models.TextField()),
                (
                    "primary_service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="primary_procedures",
                        to="knowledge.service",
                    ),
                ),
            ],
            options={
                "ordering": ("semantic_id",),
            },
        ),
        migrations.CreateModel(
            name="ServiceProcedureCandidate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("selection_predicate", models.JSONField()),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="procedure_candidates",
                        to="knowledge.service",
                    ),
                ),
                (
                    "procedure",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="service_candidates",
                        to="knowledge.procedure",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="servicecontradictionfact",
            constraint=models.UniqueConstraint(
                fields=("contradiction", "fact"), name="unique_contradiction_fact"
            ),
        ),
        migrations.AddConstraint(
            model_name="servicecontradictionfact",
            constraint=models.UniqueConstraint(
                fields=("contradiction", "position"), name="unique_contradiction_position"
            ),
        ),
        migrations.AddIndex(
            model_name="servicecontradiction",
            index=models.Index(fields=["service", "semantic_id"], name="contradiction_order_idx"),
        ),
        migrations.AddConstraint(
            model_name="servicecontradiction",
            constraint=models.CheckConstraint(
                condition=models.Q(("semantic_id__regex", ".*[^[:space:]].*")),
                name="contradiction_id_nonblank",
            ),
        ),
        migrations.AddConstraint(
            model_name="servicequestionresolvedfact",
            constraint=models.UniqueConstraint(
                fields=("question", "fact"), name="unique_question_resolved_fact"
            ),
        ),
        migrations.AddConstraint(
            model_name="servicequestionresolvedfact",
            constraint=models.UniqueConstraint(
                fields=("question", "position"), name="unique_question_resolved_position"
            ),
        ),
        migrations.AddIndex(
            model_name="servicequestion",
            index=models.Index(
                fields=["service", "priority", "semantic_id"], name="question_order_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="servicequestion",
            constraint=models.CheckConstraint(
                condition=models.Q(("semantic_id__regex", ".*[^[:space:]].*")),
                name="question_id_nonblank",
            ),
        ),
        migrations.AddConstraint(
            model_name="servicequestion",
            constraint=models.CheckConstraint(
                condition=models.Q(("text_ar__regex", ".*[^[:space:]].*")),
                name="question_ar_nonblank",
            ),
        ),
        migrations.AddConstraint(
            model_name="servicequestion",
            constraint=models.CheckConstraint(
                condition=models.Q(("text_en__regex", ".*[^[:space:]].*")),
                name="question_en_nonblank",
            ),
        ),
        migrations.AddConstraint(
            model_name="procedure",
            constraint=models.CheckConstraint(
                condition=models.Q(("semantic_id__regex", ".*[^[:space:]].*")),
                name="procedure_id_nonblank",
            ),
        ),
        migrations.AddConstraint(
            model_name="procedure",
            constraint=models.CheckConstraint(
                condition=models.Q(("text_ar__regex", ".*[^[:space:]].*")),
                name="procedure_ar_nonblank",
            ),
        ),
        migrations.AddConstraint(
            model_name="procedure",
            constraint=models.CheckConstraint(
                condition=models.Q(("text_en__regex", ".*[^[:space:]].*")),
                name="procedure_en_nonblank",
            ),
        ),
        migrations.AddIndex(
            model_name="serviceprocedurecandidate",
            index=models.Index(fields=["service", "procedure"], name="candidate_service_proc_idx"),
        ),
        migrations.AddConstraint(
            model_name="serviceprocedurecandidate",
            constraint=models.UniqueConstraint(
                fields=("service", "procedure"), name="unique_service_procedure_candidate"
            ),
        ),
        migrations.AddConstraint(
            model_name="factdefinition",
            constraint=models.CheckConstraint(
                condition=django.db.models.lookups.Exact(
                    models.Func(
                        models.F("enum_values"),
                        function="jsonb_typeof",
                        output_field=models.CharField(),
                    ),
                    models.Value("array"),
                ),
                name="fact_enum_values_array",
            ),
        ),
        migrations.RunPython(seed_facts, unseed_facts),
        migrations.RunSQL(PUBLISHED_FACT_TRIGGER_SQL, PUBLISHED_FACT_TRIGGER_REVERSE_SQL),
    ]
