# Generated by Django 5.2.17 on 2026-09-02 20:36

import django.contrib.postgres.constraints
import django.contrib.postgres.fields.ranges
import django.contrib.postgres.operations
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

LIFECYCLE_TRIGGER_SQL = r"""
CREATE FUNCTION knowledge_guard_procedure_version() RETURNS trigger AS $$
DECLARE lifecycle text := current_setting('bardi.procedure_version_lifecycle', true);
BEGIN
    IF TG_OP = 'INSERT' THEN
        IF NEW.state <> 'draft' OR NEW.published_at IS NOT NULL OR NEW.published_by_id IS NOT NULL
           OR NEW.withdrawn_at IS NOT NULL OR NEW.withdrawn_by_id IS NOT NULL THEN
            RAISE EXCEPTION 'Procedure Versions may only be inserted as drafts';
        END IF;
        RETURN NEW;
    END IF;
    IF TG_OP = 'DELETE' THEN
        IF OLD.state <> 'draft' THEN
            RAISE EXCEPTION 'published or withdrawn Procedure Versions cannot be deleted';
        END IF;
        RETURN OLD;
    END IF;
    IF OLD.state = 'draft' AND NEW.state = 'draft' THEN
        RETURN NEW;
    END IF;
    IF OLD.state = 'draft' AND NEW.state = 'published' AND lifecycle = 'publish'
       AND NEW.semantic_id IS NOT DISTINCT FROM OLD.semantic_id
       AND NEW.procedure_id IS NOT DISTINCT FROM OLD.procedure_id
       AND NEW.effective_from IS NOT DISTINCT FROM OLD.effective_from
       AND NEW.effective_to IS NOT DISTINCT FROM OLD.effective_to
       AND NEW.text_ar IS NOT DISTINCT FROM OLD.text_ar
       AND NEW.text_en IS NOT DISTINCT FROM OLD.text_en
       AND NEW.applicability IS NOT DISTINCT FROM OLD.applicability
       AND NEW.rules_contract_version IS NOT DISTINCT FROM OLD.rules_contract_version
       AND NEW.published_at IS NOT NULL AND NEW.published_by_id IS NOT NULL
       AND NEW.withdrawn_at IS NULL AND NEW.withdrawn_by_id IS NULL THEN
        RETURN NEW;
    END IF;
    IF OLD.state = 'published' AND NEW.state = 'withdrawn' AND lifecycle = 'withdraw'
       AND NEW.semantic_id IS NOT DISTINCT FROM OLD.semantic_id
       AND NEW.procedure_id IS NOT DISTINCT FROM OLD.procedure_id
       AND NEW.effective_from IS NOT DISTINCT FROM OLD.effective_from
       AND NEW.effective_to IS NOT DISTINCT FROM OLD.effective_to
       AND NEW.text_ar IS NOT DISTINCT FROM OLD.text_ar
       AND NEW.text_en IS NOT DISTINCT FROM OLD.text_en
       AND NEW.applicability IS NOT DISTINCT FROM OLD.applicability
       AND NEW.rules_contract_version IS NOT DISTINCT FROM OLD.rules_contract_version
       AND NEW.published_at IS NOT DISTINCT FROM OLD.published_at
       AND NEW.published_by_id IS NOT DISTINCT FROM OLD.published_by_id
       AND NEW.withdrawn_at IS NOT NULL AND NEW.withdrawn_by_id IS NOT NULL THEN
        RETURN NEW;
    END IF;
    RAISE EXCEPTION 'invalid Procedure Version lifecycle transition or immutable update';
END;
$$ LANGUAGE plpgsql;
CREATE TRIGGER knowledge_procedure_version_guard
BEFORE INSERT OR UPDATE OR DELETE ON knowledge_procedureversion
FOR EACH ROW EXECUTE FUNCTION knowledge_guard_procedure_version();

CREATE FUNCTION knowledge_guard_procedure_version_audit() RETURNS trigger AS $$
DECLARE lifecycle text := current_setting('bardi.procedure_version_lifecycle', true);
BEGIN
    IF TG_OP <> 'INSERT' THEN
        RAISE EXCEPTION 'Procedure Version audit events are immutable';
    END IF;
    IF (lifecycle = 'publish' AND NEW.event_type = 'published'
        AND NEW.from_state = 'draft' AND NEW.to_state = 'published')
       OR (lifecycle = 'withdraw' AND NEW.event_type = 'withdrawn'
        AND NEW.from_state = 'published' AND NEW.to_state = 'withdrawn') THEN
        RETURN NEW;
    END IF;
    RAISE EXCEPTION 'unauthorized Procedure Version audit event';
END;
$$ LANGUAGE plpgsql;
CREATE TRIGGER knowledge_procedure_version_audit_guard
BEFORE INSERT OR UPDATE OR DELETE ON knowledge_procedureversionauditevent
FOR EACH ROW EXECUTE FUNCTION knowledge_guard_procedure_version_audit();

CREATE FUNCTION knowledge_guard_published_procedure_owner() RETURNS trigger AS $$
BEGIN
    IF (NEW.semantic_id IS DISTINCT FROM OLD.semantic_id
        OR NEW.primary_service_id IS DISTINCT FROM OLD.primary_service_id)
       AND EXISTS (
           SELECT 1 FROM knowledge_procedureversion
           WHERE procedure_id = OLD.id AND state IN ('published', 'withdrawn')
       ) THEN
        RAISE EXCEPTION 'Procedure identity and ownership are protected by version history';
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;
CREATE TRIGGER knowledge_published_procedure_owner_guard
BEFORE UPDATE ON knowledge_procedure
FOR EACH ROW EXECUTE FUNCTION knowledge_guard_published_procedure_owner();
"""

LIFECYCLE_TRIGGER_REVERSE_SQL = r"""
DROP TRIGGER IF EXISTS knowledge_published_procedure_owner_guard ON knowledge_procedure;
DROP FUNCTION IF EXISTS knowledge_guard_published_procedure_owner();
DROP TRIGGER IF EXISTS knowledge_procedure_version_audit_guard
ON knowledge_procedureversionauditevent;
DROP FUNCTION IF EXISTS knowledge_guard_procedure_version_audit();
DROP TRIGGER IF EXISTS knowledge_procedure_version_guard ON knowledge_procedureversion;
DROP FUNCTION IF EXISTS knowledge_guard_procedure_version();
"""


class Migration(migrations.Migration):
    dependencies = [
        ("knowledge", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        django.contrib.postgres.operations.BtreeGistExtension(),
        migrations.CreateModel(
            name="ProcedureVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("semantic_id", models.CharField(max_length=128, unique=True)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("published", "Published"),
                            ("withdrawn", "Withdrawn"),
                        ],
                        default="draft",
                        max_length=16,
                    ),
                ),
                ("effective_from", models.DateField(blank=True, null=True)),
                ("effective_to", models.DateField(blank=True, null=True)),
                ("text_ar", models.TextField(blank=True)),
                ("text_en", models.TextField(blank=True)),
                ("applicability", models.JSONField(blank=True, default=dict)),
                ("rules_contract_version", models.CharField(default="v1", max_length=16)),
                ("published_at", models.DateTimeField(blank=True, editable=False, null=True)),
                ("withdrawn_at", models.DateTimeField(blank=True, editable=False, null=True)),
                (
                    "procedure",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="versions",
                        to="knowledge.procedure",
                    ),
                ),
                (
                    "published_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="published_procedure_versions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "withdrawn_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="withdrawn_procedure_versions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("procedure__semantic_id", "effective_from", "semantic_id"),
                "permissions": [
                    ("publish_procedureversion", "Can publish Procedure Version"),
                    ("withdraw_procedureversion", "Can withdraw Procedure Version"),
                ],
            },
        ),
        migrations.CreateModel(
            name="ProcedureVersionAuditEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[("published", "Published"), ("withdrawn", "Withdrawn")],
                        max_length=16,
                    ),
                ),
                ("occurred_at", models.DateTimeField()),
                (
                    "from_state",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("published", "Published"),
                            ("withdrawn", "Withdrawn"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "to_state",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("published", "Published"),
                            ("withdrawn", "Withdrawn"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="procedure_version_audit_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="audit_events",
                        to="knowledge.procedureversion",
                    ),
                ),
            ],
            options={
                "ordering": ("occurred_at", "id"),
            },
        ),
        migrations.AddIndex(
            model_name="procedureversion",
            index=models.Index(fields=["procedure", "state"], name="proc_version_state_idx"),
        ),
        migrations.AddIndex(
            model_name="procedureversion",
            index=models.Index(
                fields=["state", "effective_from"], name="proc_version_effective_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="procedureversion",
            constraint=models.CheckConstraint(
                condition=models.Q(("semantic_id__regex", ".*[^[:space:]].*")),
                name="proc_version_id_nonblank",
            ),
        ),
        migrations.AddConstraint(
            model_name="procedureversion",
            constraint=models.CheckConstraint(
                condition=models.Q(("state__in", ["draft", "published", "withdrawn"])),
                name="proc_version_state_supported",
            ),
        ),
        migrations.AddConstraint(
            model_name="procedureversion",
            constraint=models.CheckConstraint(
                condition=models.Q(("rules_contract_version", "v1")),
                name="proc_version_contract_supported",
            ),
        ),
        migrations.AddConstraint(
            model_name="procedureversion",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("effective_from__isnull", True),
                    ("effective_to__isnull", True),
                    ("effective_from__lte", models.F("effective_to")),
                    _connector="OR",
                ),
                name="proc_version_dates_ordered",
            ),
        ),
        migrations.AddConstraint(
            model_name="procedureversion",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("published_at__isnull", True),
                        ("published_by__isnull", True),
                        ("state", "draft"),
                        ("withdrawn_at__isnull", True),
                        ("withdrawn_by__isnull", True),
                    ),
                    models.Q(
                        ("published_at__isnull", False),
                        ("published_by__isnull", False),
                        ("state", "published"),
                        ("withdrawn_at__isnull", True),
                        ("withdrawn_by__isnull", True),
                    ),
                    models.Q(
                        ("published_at__isnull", False),
                        ("published_by__isnull", False),
                        ("state", "withdrawn"),
                        ("withdrawn_at__isnull", False),
                        ("withdrawn_by__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="proc_version_lifecycle_metadata",
            ),
        ),
        migrations.AddConstraint(
            model_name="procedureversion",
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(
                condition=models.Q(("state", "published")),
                expressions=(
                    ("procedure", "="),
                    (
                        models.Func(
                            models.F("effective_from"),
                            models.F("effective_to"),
                            models.Value("[]"),
                            function="DATERANGE",
                            output_field=django.contrib.postgres.fields.ranges.DateRangeField(),
                        ),
                        "&&",
                    ),
                ),
                name="exclude_published_proc_version_overlap",
            ),
        ),
        migrations.AddConstraint(
            model_name="procedureversionauditevent",
            constraint=models.UniqueConstraint(
                condition=models.Q(("event_type", "published")),
                fields=("version",),
                name="one_publication_event_per_version",
            ),
        ),
        migrations.AddConstraint(
            model_name="procedureversionauditevent",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("event_type", "published"),
                        ("from_state", "draft"),
                        ("to_state", "published"),
                    ),
                    models.Q(
                        ("event_type", "withdrawn"),
                        ("from_state", "published"),
                        ("to_state", "withdrawn"),
                    ),
                    _connector="OR",
                ),
                name="proc_version_audit_transition",
            ),
        ),
        migrations.RunSQL(LIFECYCLE_TRIGGER_SQL, LIFECYCLE_TRIGGER_REVERSE_SQL),
    ]
