# ruff: noqa: E501
# Generated by Django 5.2.17 on 2026-09-04 01:57

import django.db.models.deletion
from django.db import migrations, models

IMMUTABILITY_SQL = r"""
CREATE FUNCTION knowledge_checklist_owner_state(item_id bigint) RETURNS text AS $$
  SELECT pv.state FROM knowledge_checklistitem ci
  JOIN knowledge_procedureversion pv ON pv.id = ci.procedure_version_id
  WHERE ci.id = item_id;
$$ LANGUAGE sql STABLE;

CREATE FUNCTION knowledge_guard_checklist_child() RETURNS trigger AS $$
DECLARE old_owner_state text;
DECLARE new_owner_state text;
BEGIN
  IF TG_TABLE_NAME = 'knowledge_checklistitem' THEN
    IF TG_OP <> 'INSERT' THEN
      SELECT state INTO old_owner_state FROM knowledge_procedureversion
      WHERE id = OLD.procedure_version_id;
    END IF;
    IF TG_OP <> 'DELETE' THEN
      SELECT state INTO new_owner_state FROM knowledge_procedureversion
      WHERE id = NEW.procedure_version_id;
    END IF;
  ELSIF TG_TABLE_NAME = 'knowledge_evidencelink' THEN
    IF TG_OP <> 'INSERT' THEN
      old_owner_state := knowledge_checklist_owner_state(OLD.checklist_item_id);
    END IF;
    IF TG_OP <> 'DELETE' THEN
      new_owner_state := knowledge_checklist_owner_state(NEW.checklist_item_id);
    END IF;
  ELSE
    IF TG_OP <> 'INSERT' THEN
      SELECT knowledge_checklist_owner_state(el.checklist_item_id) INTO old_owner_state
      FROM knowledge_evidencelink el WHERE el.id = OLD.evidence_link_id;
    END IF;
    IF TG_OP <> 'DELETE' THEN
      SELECT knowledge_checklist_owner_state(el.checklist_item_id) INTO new_owner_state
      FROM knowledge_evidencelink el WHERE el.id = NEW.evidence_link_id;
    END IF;
  END IF;
  IF old_owner_state IN ('published', 'withdrawn')
     OR new_owner_state IN ('published', 'withdrawn') THEN
    RAISE EXCEPTION 'published checklist aggregate is immutable';
  END IF;
  RETURN COALESCE(NEW, OLD);
END;
$$ LANGUAGE plpgsql;
CREATE TRIGGER knowledge_checklist_guard BEFORE INSERT OR UPDATE OR DELETE ON knowledge_checklistitem FOR EACH ROW EXECUTE FUNCTION knowledge_guard_checklist_child();
CREATE TRIGGER knowledge_evidence_guard BEFORE INSERT OR UPDATE OR DELETE ON knowledge_evidencelink FOR EACH ROW EXECUTE FUNCTION knowledge_guard_checklist_child();
CREATE TRIGGER knowledge_evidence_source_guard BEFORE INSERT OR UPDATE OR DELETE ON knowledge_evidencelinksource FOR EACH ROW EXECUTE FUNCTION knowledge_guard_checklist_child();

CREATE FUNCTION knowledge_guard_preserved_provenance() RETURNS trigger AS $$
DECLARE is_used boolean;
BEGIN
  IF TG_TABLE_NAME = 'knowledge_source' THEN
    SELECT EXISTS(SELECT 1 FROM knowledge_evidencelinksource els JOIN knowledge_evidencelink el ON el.id=els.evidence_link_id JOIN knowledge_checklistitem ci ON ci.id=el.checklist_item_id JOIN knowledge_procedureversion pv ON pv.id=ci.procedure_version_id WHERE els.source_id=OLD.id AND pv.state IN ('published','withdrawn')) INTO is_used;
  ELSIF TG_TABLE_NAME = 'knowledge_authority' THEN
    SELECT EXISTS(SELECT 1 FROM knowledge_source s JOIN knowledge_evidencelinksource els ON els.source_id=s.id JOIN knowledge_evidencelink el ON el.id=els.evidence_link_id JOIN knowledge_checklistitem ci ON ci.id=el.checklist_item_id JOIN knowledge_procedureversion pv ON pv.id=ci.procedure_version_id WHERE s.authority_id=OLD.id AND pv.state IN ('published','withdrawn')) INTO is_used;
  ELSE
    SELECT EXISTS(SELECT 1 FROM knowledge_checklistitem ci JOIN knowledge_procedureversion pv ON pv.id=ci.procedure_version_id WHERE ci.document_type_id=OLD.id AND pv.state IN ('published','withdrawn')) INTO is_used;
  END IF;
  IF is_used THEN RAISE EXCEPTION 'published provenance identity is immutable'; END IF;
  RETURN COALESCE(NEW, OLD);
END;
$$ LANGUAGE plpgsql;
CREATE TRIGGER knowledge_source_preserved BEFORE UPDATE OR DELETE ON knowledge_source FOR EACH ROW EXECUTE FUNCTION knowledge_guard_preserved_provenance();
CREATE TRIGGER knowledge_authority_preserved BEFORE UPDATE OR DELETE ON knowledge_authority FOR EACH ROW EXECUTE FUNCTION knowledge_guard_preserved_provenance();
CREATE TRIGGER knowledge_document_type_preserved BEFORE UPDATE OR DELETE ON knowledge_documenttype FOR EACH ROW EXECUTE FUNCTION knowledge_guard_preserved_provenance();
"""

IMMUTABILITY_REVERSE_SQL = r"""
DROP TRIGGER IF EXISTS knowledge_document_type_preserved ON knowledge_documenttype;
DROP TRIGGER IF EXISTS knowledge_authority_preserved ON knowledge_authority;
DROP TRIGGER IF EXISTS knowledge_source_preserved ON knowledge_source;
DROP FUNCTION IF EXISTS knowledge_guard_preserved_provenance();
DROP TRIGGER IF EXISTS knowledge_evidence_source_guard ON knowledge_evidencelinksource;
DROP TRIGGER IF EXISTS knowledge_evidence_guard ON knowledge_evidencelink;
DROP TRIGGER IF EXISTS knowledge_checklist_guard ON knowledge_checklistitem;
DROP FUNCTION IF EXISTS knowledge_guard_checklist_child();
DROP FUNCTION IF EXISTS knowledge_checklist_owner_state(bigint);
"""


class Migration(migrations.Migration):
    dependencies = [
        ("knowledge", "0003_service_is_active"),
    ]

    operations = [
        migrations.CreateModel(
            name="Authority",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("semantic_id", models.CharField(max_length=128, unique=True)),
                ("name_ar", models.TextField()),
                ("name_en", models.TextField()),
            ],
            options={
                "ordering": ("semantic_id",),
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("semantic_id__regex", ".*[^[:space:]].*")),
                        name="authority_id_nonblank",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("name_ar__regex", ".*[^[:space:]].*")),
                        name="authority_ar_nonblank",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("name_en__regex", ".*[^[:space:]].*")),
                        name="authority_en_nonblank",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="DocumentType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("semantic_id", models.CharField(max_length=128, unique=True)),
                ("name_ar", models.TextField()),
                ("name_en", models.TextField()),
            ],
            options={
                "ordering": ("semantic_id",),
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("semantic_id__regex", ".*[^[:space:]].*")),
                        name="document_type_id_nonblank",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("name_ar__regex", ".*[^[:space:]].*")),
                        name="document_type_ar_nonblank",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("name_en__regex", ".*[^[:space:]].*")),
                        name="document_type_en_nonblank",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ChecklistItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("semantic_id", models.CharField(max_length=128)),
                ("text_ar", models.TextField()),
                ("text_en", models.TextField()),
                (
                    "classification",
                    models.CharField(
                        choices=[
                            ("official_requirement", "Official requirement"),
                            ("practical_preparation", "Practical preparation"),
                            ("candidate", "Research candidate"),
                        ],
                        max_length=32,
                    ),
                ),
                ("quantity", models.PositiveIntegerField(default=1)),
                ("original_quantity", models.PositiveIntegerField(default=0)),
                ("copy_quantity", models.PositiveIntegerField(default=0)),
                ("display_order", models.PositiveIntegerField(default=0)),
                ("applicability", models.JSONField(blank=True, default=dict)),
                (
                    "scope",
                    models.CharField(
                        choices=[
                            ("procedure", "Entire procedure"),
                            ("eligibility_basis", "Eligibility basis"),
                        ],
                        default="procedure",
                        max_length=24,
                    ),
                ),
                ("scope_reference", models.CharField(blank=True, max_length=128)),
                ("effective_from", models.DateField(blank=True, null=True)),
                ("effective_to", models.DateField(blank=True, null=True)),
                ("verified_on", models.DateField(blank=True, null=True)),
                ("reverify_on", models.DateField(blank=True, null=True)),
                (
                    "verification_state",
                    models.CharField(
                        choices=[
                            ("current", "Current"),
                            ("needs_reverification", "Needs reverification"),
                            ("stale", "Stale"),
                            ("disputed", "Disputed"),
                            ("unknown", "Unknown"),
                        ],
                        default="unknown",
                        max_length=24,
                    ),
                ),
                (
                    "procedure_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="checklist_items",
                        to="knowledge.procedureversion",
                    ),
                ),
                (
                    "document_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="checklist_items",
                        to="knowledge.documenttype",
                    ),
                ),
            ],
            options={
                "ordering": ("procedure_version_id", "display_order", "semantic_id"),
            },
        ),
        migrations.CreateModel(
            name="EvidenceLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("passage", models.TextField()),
                ("location", models.TextField(blank=True)),
                ("applicability_context", models.TextField(blank=True)),
                ("effective_from", models.DateField(blank=True, null=True)),
                ("effective_to", models.DateField(blank=True, null=True)),
                ("retrieved_on", models.DateField(blank=True, null=True)),
                ("verified_on", models.DateField(blank=True, null=True)),
                ("reverify_on", models.DateField(blank=True, null=True)),
                (
                    "verification_state",
                    models.CharField(
                        choices=[
                            ("current", "Current"),
                            ("needs_reverification", "Needs reverification"),
                            ("stale", "Stale"),
                            ("disputed", "Disputed"),
                            ("unknown", "Unknown"),
                        ],
                        default="unknown",
                        max_length=24,
                    ),
                ),
                (
                    "support_status",
                    models.CharField(
                        choices=[
                            ("supports", "Supports"),
                            ("context", "Context only"),
                            ("contradicts", "Contradicts"),
                        ],
                        default="supports",
                        max_length=16,
                    ),
                ),
                (
                    "checklist_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evidence_links",
                        to="knowledge.checklistitem",
                    ),
                ),
            ],
            options={
                "ordering": ("checklist_item_id", "id"),
            },
        ),
        migrations.CreateModel(
            name="Source",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("semantic_id", models.CharField(max_length=128, unique=True)),
                ("title", models.TextField()),
                ("locator", models.TextField()),
                (
                    "classification",
                    models.CharField(
                        choices=[
                            ("official", "Official"),
                            ("field_report", "Field report"),
                            ("secondary", "Secondary"),
                        ],
                        max_length=16,
                    ),
                ),
                ("published_on", models.DateField(blank=True, null=True)),
                ("effective_from", models.DateField(blank=True, null=True)),
                ("effective_to", models.DateField(blank=True, null=True)),
                ("retrieved_on", models.DateField()),
                ("reverify_on", models.DateField(blank=True, null=True)),
                ("observation_date", models.DateField(blank=True, null=True)),
                ("observation_context", models.TextField(blank=True)),
                (
                    "authority",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sources",
                        to="knowledge.authority",
                    ),
                ),
            ],
            options={
                "ordering": ("semantic_id",),
            },
        ),
        migrations.CreateModel(
            name="EvidenceLinkSource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("position", models.PositiveIntegerField()),
                (
                    "evidence_link",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="source_links",
                        to="knowledge.evidencelink",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="evidence_source_links",
                        to="knowledge.source",
                    ),
                ),
            ],
            options={
                "ordering": ("evidence_link_id", "position", "source__semantic_id"),
            },
        ),
        migrations.AddField(
            model_name="evidencelink",
            name="sources",
            field=models.ManyToManyField(
                related_name="evidence_links",
                through="knowledge.EvidenceLinkSource",
                to="knowledge.source",
            ),
        ),
        migrations.AddConstraint(
            model_name="checklistitem",
            constraint=models.UniqueConstraint(
                fields=("procedure_version", "semantic_id"), name="unique_checklist_id_per_version"
            ),
        ),
        migrations.AddConstraint(
            model_name="checklistitem",
            constraint=models.CheckConstraint(
                condition=models.Q(("semantic_id__regex", ".*[^[:space:]].*")),
                name="checklist_id_nonblank",
            ),
        ),
        migrations.AddConstraint(
            model_name="checklistitem",
            constraint=models.CheckConstraint(
                condition=models.Q(("text_ar__regex", ".*[^[:space:]].*")),
                name="checklist_ar_nonblank",
            ),
        ),
        migrations.AddConstraint(
            model_name="checklistitem",
            constraint=models.CheckConstraint(
                condition=models.Q(("text_en__regex", ".*[^[:space:]].*")),
                name="checklist_en_nonblank",
            ),
        ),
        migrations.AddConstraint(
            model_name="checklistitem",
            constraint=models.CheckConstraint(
                condition=models.Q(("quantity__gt", 0)), name="checklist_quantity_positive"
            ),
        ),
        migrations.AddConstraint(
            model_name="checklistitem",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("effective_from__isnull", True),
                    ("effective_to__isnull", True),
                    ("effective_from__lte", models.F("effective_to")),
                    _connector="OR",
                ),
                name="checklist_dates_ordered",
            ),
        ),
        migrations.AddConstraint(
            model_name="checklistitem",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("scope", "procedure"), ("scope_reference", "")),
                    models.Q(
                        ("scope", "eligibility_basis"),
                        ("scope_reference__regex", ".*[^[:space:]].*"),
                    ),
                    _connector="OR",
                ),
                name="checklist_scope_combination",
            ),
        ),
        migrations.AddConstraint(
            model_name="source",
            constraint=models.CheckConstraint(
                condition=models.Q(("semantic_id__regex", ".*[^[:space:]].*")),
                name="source_id_nonblank",
            ),
        ),
        migrations.AddConstraint(
            model_name="source",
            constraint=models.CheckConstraint(
                condition=models.Q(("title__regex", ".*[^[:space:]].*")),
                name="source_title_nonblank",
            ),
        ),
        migrations.AddConstraint(
            model_name="source",
            constraint=models.CheckConstraint(
                condition=models.Q(("locator__regex", ".*[^[:space:]].*")),
                name="source_locator_nonblank",
            ),
        ),
        migrations.AddConstraint(
            model_name="source",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("classification__in", ["official", "field_report", "secondary"])
                ),
                name="source_class_supported",
            ),
        ),
        migrations.AddConstraint(
            model_name="source",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("effective_from__isnull", True),
                    ("effective_to__isnull", True),
                    ("effective_from__lte", models.F("effective_to")),
                    _connector="OR",
                ),
                name="source_dates_ordered",
            ),
        ),
        migrations.AddConstraint(
            model_name="evidencelinksource",
            constraint=models.UniqueConstraint(
                fields=("evidence_link", "source"), name="unique_evidence_source"
            ),
        ),
        migrations.AddConstraint(
            model_name="evidencelinksource",
            constraint=models.UniqueConstraint(
                fields=("evidence_link", "position"), name="unique_evidence_source_position"
            ),
        ),
        migrations.AddConstraint(
            model_name="evidencelink",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("effective_from__isnull", True),
                    ("effective_to__isnull", True),
                    ("effective_from__lte", models.F("effective_to")),
                    _connector="OR",
                ),
                name="evidence_dates_ordered",
            ),
        ),
        migrations.AddConstraint(
            model_name="checklistitem",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    classification__in=[
                        "official_requirement",
                        "practical_preparation",
                        "candidate",
                    ]
                ),
                name="checklist_class_supported",
            ),
        ),
        migrations.AddConstraint(
            model_name="checklistitem",
            constraint=models.CheckConstraint(
                condition=models.Q(scope__in=["procedure", "eligibility_basis"]),
                name="checklist_scope_supported",
            ),
        ),
        migrations.AddConstraint(
            model_name="checklistitem",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    verification_state__in=[
                        "current",
                        "needs_reverification",
                        "stale",
                        "disputed",
                        "unknown",
                    ]
                ),
                name="checklist_verification_supported",
            ),
        ),
        migrations.AddConstraint(
            model_name="evidencelink",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    verification_state__in=[
                        "current",
                        "needs_reverification",
                        "stale",
                        "disputed",
                        "unknown",
                    ]
                ),
                name="evidence_verification_supported",
            ),
        ),
        migrations.AddConstraint(
            model_name="evidencelink",
            constraint=models.CheckConstraint(
                condition=models.Q(support_status__in=["supports", "context", "contradicts"]),
                name="evidence_support_supported",
            ),
        ),
        migrations.RunSQL(IMMUTABILITY_SQL, IMMUTABILITY_REVERSE_SQL),
    ]
