# ruff: noqa: E501
# Generated by Django 5.2.17 on 2026-09-05 00:20

import django.db.models.deletion
from django.db import migrations, models

GENERIC_GUARDS_SQL = r"""
DROP TRIGGER knowledge_document_type_preserved ON knowledge_documenttype;
DROP TRIGGER knowledge_authority_preserved ON knowledge_authority;
DROP TRIGGER knowledge_source_preserved ON knowledge_source;
DROP FUNCTION knowledge_guard_preserved_provenance();
DROP TRIGGER knowledge_evidence_source_guard ON knowledge_evidencelinksource;
DROP TRIGGER knowledge_evidence_guard ON knowledge_evidencelink;
DROP TRIGGER knowledge_checklist_guard ON knowledge_checklistitem;
DROP FUNCTION knowledge_guard_checklist_child();
DROP FUNCTION knowledge_checklist_owner_state(bigint);

CREATE FUNCTION knowledge_claim_version(item bigint, step bigint, warning bigint) RETURNS bigint AS $$
 SELECT COALESCE((SELECT procedure_version_id FROM knowledge_checklistitem WHERE id=item),
                 (SELECT procedure_version_id FROM knowledge_step WHERE id=step),
                 (SELECT procedure_version_id FROM knowledge_warning WHERE id=warning));
$$ LANGUAGE sql STABLE;
CREATE FUNCTION knowledge_evidence_version(link bigint) RETURNS bigint AS $$
 SELECT knowledge_claim_version(checklist_item_id, step_id, warning_id)
 FROM knowledge_evidencelink WHERE id=link;
$$ LANGUAGE sql STABLE;
CREATE FUNCTION knowledge_guard_claim_child() RETURNS trigger AS $$
DECLARE old_version bigint; DECLARE new_version bigint; DECLARE old_state text; DECLARE new_state text;
BEGIN
 IF TG_TABLE_NAME IN ('knowledge_checklistitem','knowledge_step','knowledge_warning','knowledge_eligibilitybasis') THEN
   IF TG_OP <> 'INSERT' THEN old_version := OLD.procedure_version_id; END IF;
   IF TG_OP <> 'DELETE' THEN new_version := NEW.procedure_version_id; END IF;
 ELSIF TG_TABLE_NAME = 'knowledge_evidencelink' THEN
   IF TG_OP <> 'INSERT' THEN old_version := knowledge_claim_version(OLD.checklist_item_id, OLD.step_id, OLD.warning_id); END IF;
   IF TG_OP <> 'DELETE' THEN new_version := knowledge_claim_version(NEW.checklist_item_id, NEW.step_id, NEW.warning_id); END IF;
 ELSE
   IF TG_OP <> 'INSERT' THEN old_version := knowledge_evidence_version(OLD.evidence_link_id); END IF;
   IF TG_OP <> 'DELETE' THEN new_version := knowledge_evidence_version(NEW.evidence_link_id); END IF;
 END IF;
 SELECT state INTO old_state FROM knowledge_procedureversion WHERE id=old_version;
 SELECT state INTO new_state FROM knowledge_procedureversion WHERE id=new_version;
 IF old_state IN ('published','withdrawn') OR new_state IN ('published','withdrawn') THEN
   RAISE EXCEPTION 'published guidance aggregate is immutable';
 END IF;
 RETURN COALESCE(NEW, OLD);
END; $$ LANGUAGE plpgsql;
CREATE TRIGGER knowledge_checklist_guard BEFORE INSERT OR UPDATE OR DELETE ON knowledge_checklistitem FOR EACH ROW EXECUTE FUNCTION knowledge_guard_claim_child();
CREATE TRIGGER knowledge_step_guard BEFORE INSERT OR UPDATE OR DELETE ON knowledge_step FOR EACH ROW EXECUTE FUNCTION knowledge_guard_claim_child();
CREATE TRIGGER knowledge_warning_guard BEFORE INSERT OR UPDATE OR DELETE ON knowledge_warning FOR EACH ROW EXECUTE FUNCTION knowledge_guard_claim_child();
CREATE TRIGGER knowledge_basis_guard BEFORE INSERT OR UPDATE OR DELETE ON knowledge_eligibilitybasis FOR EACH ROW EXECUTE FUNCTION knowledge_guard_claim_child();
CREATE TRIGGER knowledge_evidence_guard BEFORE INSERT OR UPDATE OR DELETE ON knowledge_evidencelink FOR EACH ROW EXECUTE FUNCTION knowledge_guard_claim_child();
CREATE TRIGGER knowledge_evidence_source_guard BEFORE INSERT OR UPDATE OR DELETE ON knowledge_evidencelinksource FOR EACH ROW EXECUTE FUNCTION knowledge_guard_claim_child();

CREATE FUNCTION knowledge_guard_preserved_provenance() RETURNS trigger AS $$
DECLARE is_used boolean;
BEGIN
 IF TG_TABLE_NAME = 'knowledge_documenttype' THEN
  SELECT EXISTS(SELECT 1 FROM knowledge_checklistitem c JOIN knowledge_procedureversion pv ON pv.id=c.procedure_version_id WHERE c.document_type_id=OLD.id AND pv.state IN ('published','withdrawn')) INTO is_used;
 ELSIF TG_TABLE_NAME = 'knowledge_source' THEN
  SELECT EXISTS(SELECT 1 FROM knowledge_evidencelinksource es JOIN knowledge_evidencelink e ON e.id=es.evidence_link_id JOIN knowledge_procedureversion pv ON pv.id=knowledge_claim_version(e.checklist_item_id,e.step_id,e.warning_id) WHERE es.source_id=OLD.id AND pv.state IN ('published','withdrawn')) INTO is_used;
 ELSE
  SELECT EXISTS(SELECT 1 FROM knowledge_source s JOIN knowledge_evidencelinksource es ON es.source_id=s.id JOIN knowledge_evidencelink e ON e.id=es.evidence_link_id JOIN knowledge_procedureversion pv ON pv.id=knowledge_claim_version(e.checklist_item_id,e.step_id,e.warning_id) WHERE s.authority_id=OLD.id AND pv.state IN ('published','withdrawn')) INTO is_used;
 END IF;
 IF is_used THEN RAISE EXCEPTION 'published provenance identity is immutable'; END IF;
 RETURN COALESCE(NEW, OLD);
END; $$ LANGUAGE plpgsql;
CREATE TRIGGER knowledge_source_preserved BEFORE UPDATE OR DELETE ON knowledge_source FOR EACH ROW EXECUTE FUNCTION knowledge_guard_preserved_provenance();
CREATE TRIGGER knowledge_authority_preserved BEFORE UPDATE OR DELETE ON knowledge_authority FOR EACH ROW EXECUTE FUNCTION knowledge_guard_preserved_provenance();
CREATE TRIGGER knowledge_document_type_preserved BEFORE UPDATE OR DELETE ON knowledge_documenttype FOR EACH ROW EXECUTE FUNCTION knowledge_guard_preserved_provenance();
"""

GENERIC_GUARDS_REVERSE_SQL = r"""
DELETE FROM knowledge_evidencelinksource WHERE evidence_link_id IN (SELECT id FROM knowledge_evidencelink WHERE step_id IS NOT NULL OR warning_id IS NOT NULL);
DELETE FROM knowledge_evidencelink WHERE step_id IS NOT NULL OR warning_id IS NOT NULL;
DROP TRIGGER knowledge_document_type_preserved ON knowledge_documenttype; DROP TRIGGER knowledge_authority_preserved ON knowledge_authority; DROP TRIGGER knowledge_source_preserved ON knowledge_source; DROP FUNCTION knowledge_guard_preserved_provenance();
DROP TRIGGER knowledge_evidence_source_guard ON knowledge_evidencelinksource; DROP TRIGGER knowledge_evidence_guard ON knowledge_evidencelink; DROP TRIGGER knowledge_basis_guard ON knowledge_eligibilitybasis; DROP TRIGGER knowledge_warning_guard ON knowledge_warning; DROP TRIGGER knowledge_step_guard ON knowledge_step; DROP TRIGGER knowledge_checklist_guard ON knowledge_checklistitem; DROP FUNCTION knowledge_guard_claim_child(); DROP FUNCTION knowledge_evidence_version(bigint); DROP FUNCTION knowledge_claim_version(bigint,bigint,bigint);
CREATE FUNCTION knowledge_checklist_owner_state(item_id bigint) RETURNS text AS $$ SELECT pv.state FROM knowledge_checklistitem ci JOIN knowledge_procedureversion pv ON pv.id=ci.procedure_version_id WHERE ci.id=item_id; $$ LANGUAGE sql STABLE;
CREATE FUNCTION knowledge_guard_checklist_child() RETURNS trigger AS $$ DECLARE old_owner_state text; DECLARE new_owner_state text; BEGIN IF TG_TABLE_NAME='knowledge_checklistitem' THEN IF TG_OP<>'INSERT' THEN SELECT state INTO old_owner_state FROM knowledge_procedureversion WHERE id=OLD.procedure_version_id; END IF; IF TG_OP<>'DELETE' THEN SELECT state INTO new_owner_state FROM knowledge_procedureversion WHERE id=NEW.procedure_version_id; END IF; ELSIF TG_TABLE_NAME='knowledge_evidencelink' THEN IF TG_OP<>'INSERT' THEN old_owner_state:=knowledge_checklist_owner_state(OLD.checklist_item_id); END IF; IF TG_OP<>'DELETE' THEN new_owner_state:=knowledge_checklist_owner_state(NEW.checklist_item_id); END IF; ELSE IF TG_OP<>'INSERT' THEN SELECT knowledge_checklist_owner_state(el.checklist_item_id) INTO old_owner_state FROM knowledge_evidencelink el WHERE el.id=OLD.evidence_link_id; END IF; IF TG_OP<>'DELETE' THEN SELECT knowledge_checklist_owner_state(el.checklist_item_id) INTO new_owner_state FROM knowledge_evidencelink el WHERE el.id=NEW.evidence_link_id; END IF; END IF; IF old_owner_state IN ('published','withdrawn') OR new_owner_state IN ('published','withdrawn') THEN RAISE EXCEPTION 'published checklist aggregate is immutable'; END IF; RETURN COALESCE(NEW,OLD); END; $$ LANGUAGE plpgsql;
CREATE TRIGGER knowledge_checklist_guard BEFORE INSERT OR UPDATE OR DELETE ON knowledge_checklistitem FOR EACH ROW EXECUTE FUNCTION knowledge_guard_checklist_child(); CREATE TRIGGER knowledge_evidence_guard BEFORE INSERT OR UPDATE OR DELETE ON knowledge_evidencelink FOR EACH ROW EXECUTE FUNCTION knowledge_guard_checklist_child(); CREATE TRIGGER knowledge_evidence_source_guard BEFORE INSERT OR UPDATE OR DELETE ON knowledge_evidencelinksource FOR EACH ROW EXECUTE FUNCTION knowledge_guard_checklist_child();
CREATE FUNCTION knowledge_guard_preserved_provenance() RETURNS trigger AS $$ DECLARE is_used boolean; BEGIN IF TG_TABLE_NAME='knowledge_source' THEN SELECT EXISTS(SELECT 1 FROM knowledge_evidencelinksource els JOIN knowledge_evidencelink el ON el.id=els.evidence_link_id JOIN knowledge_checklistitem ci ON ci.id=el.checklist_item_id JOIN knowledge_procedureversion pv ON pv.id=ci.procedure_version_id WHERE els.source_id=OLD.id AND pv.state IN ('published','withdrawn')) INTO is_used; ELSIF TG_TABLE_NAME='knowledge_authority' THEN SELECT EXISTS(SELECT 1 FROM knowledge_source s JOIN knowledge_evidencelinksource els ON els.source_id=s.id JOIN knowledge_evidencelink el ON el.id=els.evidence_link_id JOIN knowledge_checklistitem ci ON ci.id=el.checklist_item_id JOIN knowledge_procedureversion pv ON pv.id=ci.procedure_version_id WHERE s.authority_id=OLD.id AND pv.state IN ('published','withdrawn')) INTO is_used; ELSE SELECT EXISTS(SELECT 1 FROM knowledge_checklistitem ci JOIN knowledge_procedureversion pv ON pv.id=ci.procedure_version_id WHERE ci.document_type_id=OLD.id AND pv.state IN ('published','withdrawn')) INTO is_used; END IF; IF is_used THEN RAISE EXCEPTION 'published provenance identity is immutable'; END IF; RETURN COALESCE(NEW,OLD); END; $$ LANGUAGE plpgsql;
CREATE TRIGGER knowledge_source_preserved BEFORE UPDATE OR DELETE ON knowledge_source FOR EACH ROW EXECUTE FUNCTION knowledge_guard_preserved_provenance(); CREATE TRIGGER knowledge_authority_preserved BEFORE UPDATE OR DELETE ON knowledge_authority FOR EACH ROW EXECUTE FUNCTION knowledge_guard_preserved_provenance(); CREATE TRIGGER knowledge_document_type_preserved BEFORE UPDATE OR DELETE ON knowledge_documenttype FOR EACH ROW EXECUTE FUNCTION knowledge_guard_preserved_provenance();
"""


class Migration(migrations.Migration):
    dependencies = [
        ("knowledge", "0004_checklist_items"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="evidencelink",
            options={"ordering": ("id",)},
        ),
        migrations.AlterField(
            model_name="evidencelink",
            name="checklist_item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="evidence_links",
                to="knowledge.checklistitem",
            ),
        ),
        migrations.CreateModel(
            name="EligibilityBasis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("semantic_id", models.CharField(max_length=128)),
                (
                    "procedure_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="eligibility_bases",
                        to="knowledge.procedureversion",
                    ),
                ),
            ],
            options={
                "ordering": ("procedure_version_id", "semantic_id"),
            },
        ),
        migrations.CreateModel(
            name="Step",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("semantic_id", models.CharField(max_length=128)),
                ("text_ar", models.TextField()),
                ("text_en", models.TextField()),
                ("phase", models.CharField(max_length=128)),
                ("phase_order", models.PositiveIntegerField(default=0)),
                ("slot", models.PositiveIntegerField(default=0)),
                ("applicability", models.JSONField(blank=True, default=dict)),
                (
                    "scope",
                    models.CharField(
                        choices=[
                            ("procedure", "Entire procedure"),
                            ("eligibility_basis", "Eligibility basis"),
                        ],
                        default="procedure",
                        max_length=24,
                    ),
                ),
                ("effective_from", models.DateField(blank=True, null=True)),
                ("effective_to", models.DateField(blank=True, null=True)),
                ("verified_on", models.DateField(blank=True, null=True)),
                ("reverify_on", models.DateField(blank=True, null=True)),
                (
                    "verification_state",
                    models.CharField(
                        choices=[
                            ("current", "Current"),
                            ("needs_reverification", "Needs reverification"),
                            ("stale", "Stale"),
                            ("disputed", "Disputed"),
                            ("unknown", "Unknown"),
                        ],
                        default="unknown",
                        max_length=24,
                    ),
                ),
                (
                    "eligibility_basis",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="steps",
                        to="knowledge.eligibilitybasis",
                    ),
                ),
                (
                    "procedure_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="steps",
                        to="knowledge.procedureversion",
                    ),
                ),
            ],
            options={
                "ordering": ("procedure_version_id", "phase_order", "slot", "semantic_id"),
            },
        ),
        migrations.AddField(
            model_name="evidencelink",
            name="step",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="evidence_links",
                to="knowledge.step",
            ),
        ),
        migrations.CreateModel(
            name="Warning",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("semantic_id", models.CharField(max_length=128)),
                ("text_ar", models.TextField()),
                ("text_en", models.TextField()),
                (
                    "severity",
                    models.CharField(
                        choices=[("info", "Information"), ("important", "Important")],
                        default="info",
                        max_length=16,
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[("administrative", "Administrative"), ("product", "Product")],
                        max_length=16,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("general", "General"),
                            ("regeneration", "Regeneration"),
                            ("limitation", "Limitation"),
                        ],
                        default="general",
                        max_length=16,
                    ),
                ),
                ("display_order", models.PositiveIntegerField(default=0)),
                ("applicability", models.JSONField(blank=True, default=dict)),
                ("effective_from", models.DateField(blank=True, null=True)),
                ("effective_to", models.DateField(blank=True, null=True)),
                ("verified_on", models.DateField(blank=True, null=True)),
                ("reverify_on", models.DateField(blank=True, null=True)),
                (
                    "verification_state",
                    models.CharField(
                        choices=[
                            ("current", "Current"),
                            ("needs_reverification", "Needs reverification"),
                            ("stale", "Stale"),
                            ("disputed", "Disputed"),
                            ("unknown", "Unknown"),
                        ],
                        default="unknown",
                        max_length=24,
                    ),
                ),
                (
                    "procedure_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="warnings",
                        to="knowledge.procedureversion",
                    ),
                ),
            ],
            options={
                "ordering": ("procedure_version_id", "display_order", "semantic_id"),
            },
        ),
        migrations.AddField(
            model_name="evidencelink",
            name="warning",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="evidence_links",
                to="knowledge.warning",
            ),
        ),
        migrations.AddConstraint(
            model_name="evidencelink",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("checklist_item__isnull", False),
                        ("step__isnull", True),
                        ("warning__isnull", True),
                    ),
                    models.Q(
                        ("checklist_item__isnull", True),
                        ("step__isnull", False),
                        ("warning__isnull", True),
                    ),
                    models.Q(
                        ("checklist_item__isnull", True),
                        ("step__isnull", True),
                        ("warning__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="evidence_exactly_one_owner",
            ),
        ),
        migrations.AddConstraint(
            model_name="eligibilitybasis",
            constraint=models.UniqueConstraint(
                fields=("procedure_version", "semantic_id"), name="unique_basis_id_per_version"
            ),
        ),
        migrations.AddConstraint(
            model_name="eligibilitybasis",
            constraint=models.CheckConstraint(
                condition=models.Q(("semantic_id__regex", ".*[^[:space:]].*")),
                name="basis_id_nonblank",
            ),
        ),
        migrations.AddConstraint(
            model_name="step",
            constraint=models.UniqueConstraint(
                fields=("procedure_version", "semantic_id"), name="unique_step_id_per_version"
            ),
        ),
        migrations.AddConstraint(
            model_name="step",
            constraint=models.UniqueConstraint(
                condition=models.Q(("verification_state", "current")),
                fields=("procedure_version", "phase_order", "slot"),
                name="unique_current_step_position",
            ),
        ),
        migrations.AddConstraint(
            model_name="step",
            constraint=models.CheckConstraint(
                condition=models.Q(("semantic_id__regex", ".*[^[:space:]].*")),
                name="step_id_nonblank",
            ),
        ),
        migrations.AddConstraint(
            model_name="step",
            constraint=models.CheckConstraint(
                condition=models.Q(("text_ar__regex", ".*[^[:space:]].*")), name="step_ar_nonblank"
            ),
        ),
        migrations.AddConstraint(
            model_name="step",
            constraint=models.CheckConstraint(
                condition=models.Q(("text_en__regex", ".*[^[:space:]].*")), name="step_en_nonblank"
            ),
        ),
        migrations.AddConstraint(
            model_name="step",
            constraint=models.CheckConstraint(
                condition=models.Q(("phase__regex", ".*[^[:space:]].*")), name="step_phase_nonblank"
            ),
        ),
        migrations.AddConstraint(
            model_name="step",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("eligibility_basis__isnull", True), ("scope", "procedure")),
                    models.Q(("eligibility_basis__isnull", False), ("scope", "eligibility_basis")),
                    _connector="OR",
                ),
                name="step_scope_combination",
            ),
        ),
        migrations.AddConstraint(
            model_name="step",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("effective_from__isnull", True),
                    ("effective_to__isnull", True),
                    ("effective_from__lte", models.F("effective_to")),
                    _connector="OR",
                ),
                name="step_dates_ordered",
            ),
        ),
        migrations.AddConstraint(
            model_name="step",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "verification_state__in",
                        ["current", "needs_reverification", "stale", "disputed", "unknown"],
                    )
                ),
                name="step_verification_supported",
            ),
        ),
        migrations.AddConstraint(
            model_name="warning",
            constraint=models.UniqueConstraint(
                fields=("procedure_version", "semantic_id"), name="unique_warning_id_per_version"
            ),
        ),
        migrations.AddConstraint(
            model_name="warning",
            constraint=models.CheckConstraint(
                condition=models.Q(("semantic_id__regex", ".*[^[:space:]].*")),
                name="warning_id_nonblank",
            ),
        ),
        migrations.AddConstraint(
            model_name="warning",
            constraint=models.CheckConstraint(
                condition=models.Q(("text_ar__regex", ".*[^[:space:]].*")),
                name="warning_ar_nonblank",
            ),
        ),
        migrations.AddConstraint(
            model_name="warning",
            constraint=models.CheckConstraint(
                condition=models.Q(("text_en__regex", ".*[^[:space:]].*")),
                name="warning_en_nonblank",
            ),
        ),
        migrations.AddConstraint(
            model_name="warning",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("role", "regeneration"), _negated=True),
                    models.Q(("kind", "product"), ("severity", "important")),
                    _connector="OR",
                ),
                name="warning_regeneration_policy",
            ),
        ),
        migrations.AddConstraint(
            model_name="warning",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("effective_from__isnull", True),
                    ("effective_to__isnull", True),
                    ("effective_from__lte", models.F("effective_to")),
                    _connector="OR",
                ),
                name="warning_dates_ordered",
            ),
        ),
        migrations.AddConstraint(
            model_name="warning",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "verification_state__in",
                        ["current", "needs_reverification", "stale", "disputed", "unknown"],
                    )
                ),
                name="warning_verification_supported",
            ),
        ),
        migrations.AddConstraint(
            model_name="warning",
            constraint=models.CheckConstraint(
                condition=models.Q(severity__in=["info", "important"]),
                name="warning_severity_supported",
            ),
        ),
        migrations.AddConstraint(
            model_name="warning",
            constraint=models.CheckConstraint(
                condition=models.Q(kind__in=["administrative", "product"]),
                name="warning_kind_supported",
            ),
        ),
        migrations.AddConstraint(
            model_name="warning",
            constraint=models.CheckConstraint(
                condition=models.Q(role__in=["general", "regeneration", "limitation"]),
                name="warning_role_supported",
            ),
        ),
        migrations.RunSQL(GENERIC_GUARDS_SQL, GENERIC_GUARDS_REVERSE_SQL),
    ]
