# ruff: noqa: E501, I001
# Generated by Django 5.2.17 on 2026-09-05 15:56

import django.contrib.postgres.constraints
import django.db.models.deletion
from django.contrib.postgres.fields import DateRangeField
from django.db import migrations, models

from importlib import import_module

DEPENDENCY_GUARDS_SQL = import_module(
    "knowledge.migrations.0008_procedure_dependencies"
).DEPENDENCY_GUARDS_SQL


ROUTING_GUARDS_SQL = r"""
DROP TRIGGER knowledge_document_type_preserved ON knowledge_documenttype;
DROP TRIGGER knowledge_authority_preserved ON knowledge_authority;
DROP TRIGGER knowledge_source_preserved ON knowledge_source;
DROP FUNCTION knowledge_guard_preserved_provenance();
DROP TRIGGER knowledge_evidence_source_guard ON knowledge_evidencelinksource;
DROP TRIGGER knowledge_evidence_guard ON knowledge_evidencelink;
DROP TRIGGER knowledge_dependency_guard ON knowledge_proceduredependency;
DROP TRIGGER knowledge_basis_guard ON knowledge_eligibilitybasis;
DROP TRIGGER knowledge_fee_guard ON knowledge_fee;
DROP TRIGGER knowledge_warning_guard ON knowledge_warning;
DROP TRIGGER knowledge_step_guard ON knowledge_step;
DROP TRIGGER knowledge_checklist_guard ON knowledge_checklistitem;
DROP FUNCTION knowledge_guard_claim_child();
DROP FUNCTION knowledge_evidence_version(bigint);
DROP FUNCTION knowledge_claim_version(bigint,bigint,bigint,bigint,bigint,bigint);

CREATE FUNCTION knowledge_claim_version(item bigint, step bigint, warning bigint, fee bigint, basis bigint, dependency bigint, material bigint, association bigint) RETURNS bigint AS $$
 SELECT COALESCE((SELECT procedure_version_id FROM knowledge_checklistitem WHERE id=item),
 (SELECT procedure_version_id FROM knowledge_step WHERE id=step), (SELECT procedure_version_id FROM knowledge_warning WHERE id=warning),
 (SELECT procedure_version_id FROM knowledge_fee WHERE id=fee), (SELECT procedure_version_id FROM knowledge_eligibilitybasis WHERE id=basis),
 (SELECT procedure_version_id FROM knowledge_proceduredependency WHERE id=dependency),
 (SELECT MIN(procedure_version_id) FROM knowledge_procedureservicepointassociation WHERE service_point_version_id=material),
 (SELECT procedure_version_id FROM knowledge_procedureservicepointassociation WHERE id=association));
$$ LANGUAGE sql STABLE;
CREATE FUNCTION knowledge_evidence_version(link bigint) RETURNS bigint AS $$
 SELECT knowledge_claim_version(checklist_item_id,step_id,warning_id,fee_id,eligibility_basis_id,procedure_dependency_id,service_point_version_id,procedure_service_point_association_id)
 FROM knowledge_evidencelink WHERE id=link;
$$ LANGUAGE sql STABLE;
CREATE FUNCTION knowledge_guard_claim_child() RETURNS trigger AS $$
DECLARE old_version bigint; DECLARE new_version bigint; DECLARE old_state text; DECLARE new_state text; DECLARE route_locked boolean;
BEGIN
 IF TG_TABLE_NAME IN ('knowledge_checklistitem','knowledge_step','knowledge_warning','knowledge_fee','knowledge_eligibilitybasis','knowledge_proceduredependency','knowledge_procedureservicepointassociation') THEN
  IF TG_OP <> 'INSERT' THEN old_version := OLD.procedure_version_id; END IF; IF TG_OP <> 'DELETE' THEN new_version := NEW.procedure_version_id; END IF;
 ELSIF TG_TABLE_NAME = 'knowledge_evidencelink' THEN
  IF TG_OP <> 'INSERT' THEN
   old_version := knowledge_claim_version(OLD.checklist_item_id,OLD.step_id,OLD.warning_id,OLD.fee_id,OLD.eligibility_basis_id,OLD.procedure_dependency_id,OLD.service_point_version_id,OLD.procedure_service_point_association_id);
   IF OLD.service_point_version_id IS NOT NULL THEN SELECT EXISTS(SELECT 1 FROM knowledge_procedureservicepointassociation a JOIN knowledge_procedureversion pv ON pv.id=a.procedure_version_id WHERE a.service_point_version_id=OLD.service_point_version_id AND pv.state IN ('published','withdrawn')) INTO route_locked; END IF;
  END IF;
  IF TG_OP <> 'DELETE' THEN
   new_version := knowledge_claim_version(NEW.checklist_item_id,NEW.step_id,NEW.warning_id,NEW.fee_id,NEW.eligibility_basis_id,NEW.procedure_dependency_id,NEW.service_point_version_id,NEW.procedure_service_point_association_id);
   IF NEW.service_point_version_id IS NOT NULL THEN SELECT route_locked OR EXISTS(SELECT 1 FROM knowledge_procedureservicepointassociation a JOIN knowledge_procedureversion pv ON pv.id=a.procedure_version_id WHERE a.service_point_version_id=NEW.service_point_version_id AND pv.state IN ('published','withdrawn')) INTO route_locked; END IF;
  END IF;
 ELSE
  IF TG_OP <> 'INSERT' THEN old_version := knowledge_evidence_version(OLD.evidence_link_id); SELECT EXISTS(SELECT 1 FROM knowledge_evidencelink e JOIN knowledge_procedureservicepointassociation a ON a.service_point_version_id=e.service_point_version_id JOIN knowledge_procedureversion pv ON pv.id=a.procedure_version_id WHERE e.id=OLD.evidence_link_id AND pv.state IN ('published','withdrawn')) INTO route_locked; END IF;
  IF TG_OP <> 'DELETE' THEN new_version := knowledge_evidence_version(NEW.evidence_link_id); SELECT route_locked OR EXISTS(SELECT 1 FROM knowledge_evidencelink e JOIN knowledge_procedureservicepointassociation a ON a.service_point_version_id=e.service_point_version_id JOIN knowledge_procedureversion pv ON pv.id=a.procedure_version_id WHERE e.id=NEW.evidence_link_id AND pv.state IN ('published','withdrawn')) INTO route_locked; END IF;
 END IF;
 SELECT state INTO old_state FROM knowledge_procedureversion WHERE id=old_version; SELECT state INTO new_state FROM knowledge_procedureversion WHERE id=new_version;
 IF COALESCE(route_locked,false) OR old_state IN ('published','withdrawn') OR new_state IN ('published','withdrawn') THEN RAISE EXCEPTION 'published guidance aggregate is immutable'; END IF;
 RETURN COALESCE(NEW,OLD);
END; $$ LANGUAGE plpgsql;
CREATE TRIGGER knowledge_checklist_guard BEFORE INSERT OR UPDATE OR DELETE ON knowledge_checklistitem FOR EACH ROW EXECUTE FUNCTION knowledge_guard_claim_child();
CREATE TRIGGER knowledge_step_guard BEFORE INSERT OR UPDATE OR DELETE ON knowledge_step FOR EACH ROW EXECUTE FUNCTION knowledge_guard_claim_child();
CREATE TRIGGER knowledge_warning_guard BEFORE INSERT OR UPDATE OR DELETE ON knowledge_warning FOR EACH ROW EXECUTE FUNCTION knowledge_guard_claim_child();
CREATE TRIGGER knowledge_fee_guard BEFORE INSERT OR UPDATE OR DELETE ON knowledge_fee FOR EACH ROW EXECUTE FUNCTION knowledge_guard_claim_child();
CREATE TRIGGER knowledge_basis_guard BEFORE INSERT OR UPDATE OR DELETE ON knowledge_eligibilitybasis FOR EACH ROW EXECUTE FUNCTION knowledge_guard_claim_child();
CREATE TRIGGER knowledge_dependency_guard BEFORE INSERT OR UPDATE OR DELETE ON knowledge_proceduredependency FOR EACH ROW EXECUTE FUNCTION knowledge_guard_claim_child();
CREATE TRIGGER knowledge_route_association_guard BEFORE INSERT OR UPDATE OR DELETE ON knowledge_procedureservicepointassociation FOR EACH ROW EXECUTE FUNCTION knowledge_guard_claim_child();
CREATE TRIGGER knowledge_evidence_guard BEFORE INSERT OR UPDATE OR DELETE ON knowledge_evidencelink FOR EACH ROW EXECUTE FUNCTION knowledge_guard_claim_child();
CREATE TRIGGER knowledge_evidence_source_guard BEFORE INSERT OR UPDATE OR DELETE ON knowledge_evidencelinksource FOR EACH ROW EXECUTE FUNCTION knowledge_guard_claim_child();

CREATE FUNCTION knowledge_guard_route_material() RETURNS trigger AS $$ DECLARE used boolean; BEGIN
 IF TG_TABLE_NAME='knowledge_servicepoint' THEN SELECT EXISTS(SELECT 1 FROM knowledge_servicepointversion sv JOIN knowledge_procedureservicepointassociation a ON a.service_point_version_id=sv.id JOIN knowledge_procedureversion pv ON pv.id=a.procedure_version_id WHERE sv.service_point_id=OLD.id AND pv.state IN ('published','withdrawn')) INTO used;
 ELSE SELECT EXISTS(SELECT 1 FROM knowledge_procedureservicepointassociation a JOIN knowledge_procedureversion pv ON pv.id=a.procedure_version_id WHERE a.service_point_version_id=OLD.id AND pv.state IN ('published','withdrawn')) INTO used; END IF;
 IF used THEN RAISE EXCEPTION 'published routing material is immutable'; END IF; RETURN COALESCE(NEW,OLD); END; $$ LANGUAGE plpgsql;
CREATE TRIGGER knowledge_service_point_guard BEFORE UPDATE OR DELETE ON knowledge_servicepoint FOR EACH ROW EXECUTE FUNCTION knowledge_guard_route_material();
CREATE TRIGGER knowledge_service_point_version_guard BEFORE UPDATE OR DELETE ON knowledge_servicepointversion FOR EACH ROW EXECUTE FUNCTION knowledge_guard_route_material();

CREATE FUNCTION knowledge_guard_preserved_provenance() RETURNS trigger AS $$ DECLARE is_used boolean; BEGIN
 IF TG_TABLE_NAME='knowledge_documenttype' THEN SELECT EXISTS(SELECT 1 FROM knowledge_checklistitem c JOIN knowledge_procedureversion pv ON pv.id=c.procedure_version_id WHERE c.document_type_id=OLD.id AND pv.state IN ('published','withdrawn')) INTO is_used;
 ELSIF TG_TABLE_NAME='knowledge_source' THEN SELECT EXISTS(SELECT 1 FROM knowledge_evidencelinksource es JOIN knowledge_evidencelink e ON e.id=es.evidence_link_id LEFT JOIN knowledge_procedureservicepointassociation ma ON ma.service_point_version_id=e.service_point_version_id JOIN knowledge_procedureversion pv ON pv.id=COALESCE(knowledge_claim_version(e.checklist_item_id,e.step_id,e.warning_id,e.fee_id,e.eligibility_basis_id,e.procedure_dependency_id,NULL,e.procedure_service_point_association_id),ma.procedure_version_id) WHERE es.source_id=OLD.id AND pv.state IN ('published','withdrawn')) INTO is_used;
 ELSE SELECT EXISTS(SELECT 1 FROM knowledge_source s JOIN knowledge_evidencelinksource es ON es.source_id=s.id JOIN knowledge_evidencelink e ON e.id=es.evidence_link_id LEFT JOIN knowledge_procedureservicepointassociation ma ON ma.service_point_version_id=e.service_point_version_id JOIN knowledge_procedureversion pv ON pv.id=COALESCE(knowledge_claim_version(e.checklist_item_id,e.step_id,e.warning_id,e.fee_id,e.eligibility_basis_id,e.procedure_dependency_id,NULL,e.procedure_service_point_association_id),ma.procedure_version_id) WHERE s.authority_id=OLD.id AND pv.state IN ('published','withdrawn')) INTO is_used; END IF;
 IF is_used THEN RAISE EXCEPTION 'published provenance identity is immutable'; END IF; RETURN COALESCE(NEW,OLD); END; $$ LANGUAGE plpgsql;
CREATE TRIGGER knowledge_source_preserved BEFORE UPDATE OR DELETE ON knowledge_source FOR EACH ROW EXECUTE FUNCTION knowledge_guard_preserved_provenance();
CREATE TRIGGER knowledge_authority_preserved BEFORE UPDATE OR DELETE ON knowledge_authority FOR EACH ROW EXECUTE FUNCTION knowledge_guard_preserved_provenance();
CREATE TRIGGER knowledge_document_type_preserved BEFORE UPDATE OR DELETE ON knowledge_documenttype FOR EACH ROW EXECUTE FUNCTION knowledge_guard_preserved_provenance();
"""

DEPENDENCY_GUARDS_CREATE_SQL = DEPENDENCY_GUARDS_SQL[
    DEPENDENCY_GUARDS_SQL.index("CREATE FUNCTION knowledge_claim_version") :
]
ROUTING_GUARDS_REVERSE_SQL = (
    r"""
DELETE FROM knowledge_evidencelinksource WHERE evidence_link_id IN (SELECT id FROM knowledge_evidencelink WHERE service_point_version_id IS NOT NULL OR procedure_service_point_association_id IS NOT NULL);
DELETE FROM knowledge_evidencelink WHERE service_point_version_id IS NOT NULL OR procedure_service_point_association_id IS NOT NULL;
DROP TRIGGER knowledge_service_point_guard ON knowledge_servicepoint;
DROP TRIGGER knowledge_service_point_version_guard ON knowledge_servicepointversion;
DROP FUNCTION knowledge_guard_route_material();
DROP TRIGGER knowledge_document_type_preserved ON knowledge_documenttype;
DROP TRIGGER knowledge_authority_preserved ON knowledge_authority;
DROP TRIGGER knowledge_source_preserved ON knowledge_source;
DROP FUNCTION knowledge_guard_preserved_provenance();
DROP TRIGGER knowledge_evidence_source_guard ON knowledge_evidencelinksource;
DROP TRIGGER knowledge_evidence_guard ON knowledge_evidencelink;
DROP TRIGGER knowledge_route_association_guard ON knowledge_procedureservicepointassociation;
DROP TRIGGER knowledge_dependency_guard ON knowledge_proceduredependency;
DROP TRIGGER knowledge_basis_guard ON knowledge_eligibilitybasis;
DROP TRIGGER knowledge_fee_guard ON knowledge_fee;
DROP TRIGGER knowledge_warning_guard ON knowledge_warning;
DROP TRIGGER knowledge_step_guard ON knowledge_step;
DROP TRIGGER knowledge_checklist_guard ON knowledge_checklistitem;
DROP FUNCTION knowledge_guard_claim_child();
DROP FUNCTION knowledge_evidence_version(bigint);
DROP FUNCTION knowledge_claim_version(bigint,bigint,bigint,bigint,bigint,bigint,bigint,bigint);
"""
    + DEPENDENCY_GUARDS_CREATE_SQL
)


class Migration(migrations.Migration):
    dependencies = [
        ("knowledge", "0008_procedure_dependencies"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProcedureServicePointAssociation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("semantic_id", models.CharField(max_length=128)),
                ("applicability", models.JSONField()),
                ("effective_from", models.DateField(blank=True, null=True)),
                ("effective_to", models.DateField(blank=True, null=True)),
                ("verified_on", models.DateField(blank=True, null=True)),
                ("reverify_on", models.DateField(blank=True, null=True)),
                (
                    "verification_state",
                    models.CharField(
                        choices=[
                            ("current", "Current"),
                            ("needs_reverification", "Needs reverification"),
                            ("stale", "Stale"),
                            ("disputed", "Disputed"),
                            ("unknown", "Unknown"),
                        ],
                        default="unknown",
                        max_length=24,
                    ),
                ),
            ],
            options={
                "ordering": ("procedure_version_id", "semantic_id"),
            },
        ),
        migrations.CreateModel(
            name="ServicePoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("semantic_id", models.CharField(max_length=128, unique=True)),
                ("name_ar", models.TextField()),
                ("name_en", models.TextField()),
            ],
            options={
                "ordering": ("semantic_id",),
            },
        ),
        migrations.CreateModel(
            name="ServicePointVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("semantic_id", models.CharField(max_length=128, unique=True)),
                ("address_ar", models.TextField()),
                ("address_en", models.TextField()),
                (
                    "availability",
                    models.CharField(
                        choices=[("available", "Available"), ("unknown", "Unknown")], max_length=16
                    ),
                ),
                ("effective_from", models.DateField(blank=True, null=True)),
                ("effective_to", models.DateField(blank=True, null=True)),
                ("verified_on", models.DateField(blank=True, null=True)),
                ("reverify_on", models.DateField(blank=True, null=True)),
                (
                    "verification_state",
                    models.CharField(
                        choices=[
                            ("current", "Current"),
                            ("needs_reverification", "Needs reverification"),
                            ("stale", "Stale"),
                            ("disputed", "Disputed"),
                            ("unknown", "Unknown"),
                        ],
                        default="unknown",
                        max_length=24,
                    ),
                ),
            ],
            options={
                "ordering": ("service_point_id", "effective_from", "semantic_id"),
            },
        ),
        migrations.RemoveConstraint(
            model_name="evidencelink",
            name="evidence_exactly_one_owner",
        ),
        migrations.AddField(
            model_name="procedureservicepointassociation",
            name="procedure_version",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="service_point_associations",
                to="knowledge.procedureversion",
            ),
        ),
        migrations.AddField(
            model_name="evidencelink",
            name="procedure_service_point_association",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="evidence_links",
                to="knowledge.procedureservicepointassociation",
            ),
        ),
        migrations.AddConstraint(
            model_name="servicepoint",
            constraint=models.CheckConstraint(
                condition=models.Q(("semantic_id__regex", ".*[^[:space:]].*")),
                name="service_point_id_nonblank",
            ),
        ),
        migrations.AddConstraint(
            model_name="servicepoint",
            constraint=models.CheckConstraint(
                condition=models.Q(("name_ar__regex", ".*[^[:space:]].*")),
                name="service_point_ar_nonblank",
            ),
        ),
        migrations.AddConstraint(
            model_name="servicepoint",
            constraint=models.CheckConstraint(
                condition=models.Q(("name_en__regex", ".*[^[:space:]].*")),
                name="service_point_en_nonblank",
            ),
        ),
        migrations.AddField(
            model_name="servicepointversion",
            name="service_point",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="versions",
                to="knowledge.servicepoint",
            ),
        ),
        migrations.AddField(
            model_name="procedureservicepointassociation",
            name="service_point_version",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="associations",
                to="knowledge.servicepointversion",
            ),
        ),
        migrations.AddField(
            model_name="evidencelink",
            name="service_point_version",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="evidence_links",
                to="knowledge.servicepointversion",
            ),
        ),
        migrations.AddConstraint(
            model_name="evidencelink",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("checklist_item__isnull", False),
                        ("eligibility_basis__isnull", True),
                        ("fee__isnull", True),
                        ("procedure_dependency__isnull", True),
                        ("procedure_service_point_association__isnull", True),
                        ("service_point_version__isnull", True),
                        ("step__isnull", True),
                        ("warning__isnull", True),
                    ),
                    models.Q(
                        ("checklist_item__isnull", True),
                        ("eligibility_basis__isnull", True),
                        ("fee__isnull", True),
                        ("procedure_dependency__isnull", True),
                        ("procedure_service_point_association__isnull", True),
                        ("service_point_version__isnull", True),
                        ("step__isnull", False),
                        ("warning__isnull", True),
                    ),
                    models.Q(
                        ("checklist_item__isnull", True),
                        ("eligibility_basis__isnull", True),
                        ("fee__isnull", True),
                        ("procedure_dependency__isnull", True),
                        ("procedure_service_point_association__isnull", True),
                        ("service_point_version__isnull", True),
                        ("step__isnull", True),
                        ("warning__isnull", False),
                    ),
                    models.Q(
                        ("checklist_item__isnull", True),
                        ("eligibility_basis__isnull", True),
                        ("fee__isnull", False),
                        ("procedure_dependency__isnull", True),
                        ("procedure_service_point_association__isnull", True),
                        ("service_point_version__isnull", True),
                        ("step__isnull", True),
                        ("warning__isnull", True),
                    ),
                    models.Q(
                        ("checklist_item__isnull", True),
                        ("eligibility_basis__isnull", False),
                        ("fee__isnull", True),
                        ("procedure_dependency__isnull", True),
                        ("procedure_service_point_association__isnull", True),
                        ("service_point_version__isnull", True),
                        ("step__isnull", True),
                        ("warning__isnull", True),
                    ),
                    models.Q(
                        ("checklist_item__isnull", True),
                        ("eligibility_basis__isnull", True),
                        ("fee__isnull", True),
                        ("procedure_dependency__isnull", False),
                        ("procedure_service_point_association__isnull", True),
                        ("service_point_version__isnull", True),
                        ("step__isnull", True),
                        ("warning__isnull", True),
                    ),
                    models.Q(
                        ("checklist_item__isnull", True),
                        ("eligibility_basis__isnull", True),
                        ("fee__isnull", True),
                        ("procedure_dependency__isnull", True),
                        ("procedure_service_point_association__isnull", True),
                        ("service_point_version__isnull", False),
                        ("step__isnull", True),
                        ("warning__isnull", True),
                    ),
                    models.Q(
                        ("checklist_item__isnull", True),
                        ("eligibility_basis__isnull", True),
                        ("fee__isnull", True),
                        ("procedure_dependency__isnull", True),
                        ("procedure_service_point_association__isnull", False),
                        ("service_point_version__isnull", True),
                        ("step__isnull", True),
                        ("warning__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="evidence_exactly_one_owner",
            ),
        ),
        migrations.AddConstraint(
            model_name="servicepointversion",
            constraint=models.CheckConstraint(
                condition=models.Q(("semantic_id__regex", ".*[^[:space:]].*")),
                name="service_point_version_id_nonblank",
            ),
        ),
        migrations.AddConstraint(
            model_name="servicepointversion",
            constraint=models.CheckConstraint(
                condition=models.Q(("address_ar__regex", ".*[^[:space:]].*")),
                name="service_point_address_ar_nonblank",
            ),
        ),
        migrations.AddConstraint(
            model_name="servicepointversion",
            constraint=models.CheckConstraint(
                condition=models.Q(("address_en__regex", ".*[^[:space:]].*")),
                name="service_point_address_en_nonblank",
            ),
        ),
        migrations.AddConstraint(
            model_name="servicepointversion",
            constraint=models.CheckConstraint(
                condition=models.Q(("availability__in", ["available", "unknown"])),
                name="service_point_availability_supported",
            ),
        ),
        migrations.AddConstraint(
            model_name="servicepointversion",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("effective_from__isnull", True),
                    ("effective_to__isnull", True),
                    ("effective_from__lte", models.F("effective_to")),
                    _connector="OR",
                ),
                name="service_point_version_dates_ordered",
            ),
        ),
        migrations.AddConstraint(
            model_name="servicepointversion",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "verification_state__in",
                        ["current", "needs_reverification", "stale", "disputed", "unknown"],
                    )
                ),
                name="service_point_version_verification_supported",
            ),
        ),
        migrations.AddConstraint(
            model_name="servicepointversion",
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(
                condition=models.Q(("verification_state", "current")),
                expressions=(
                    ("service_point", "="),
                    (
                        models.Func(
                            "effective_from",
                            "effective_to",
                            models.Value("[]"),
                            function="DATERANGE",
                            output_field=DateRangeField(),
                        ),
                        "&&",
                    ),
                ),
                name="exclude_current_service_point_version_overlap",
            ),
        ),
        migrations.AddConstraint(
            model_name="procedureservicepointassociation",
            constraint=models.UniqueConstraint(
                fields=("procedure_version", "semantic_id"),
                name="unique_service_point_association_id_per_version",
            ),
        ),
        migrations.AddConstraint(
            model_name="procedureservicepointassociation",
            constraint=models.CheckConstraint(
                condition=models.Q(("semantic_id__regex", ".*[^[:space:]].*")),
                name="service_point_association_id_nonblank",
            ),
        ),
        migrations.AddConstraint(
            model_name="procedureservicepointassociation",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("effective_from__isnull", True),
                    ("effective_to__isnull", True),
                    ("effective_from__lte", models.F("effective_to")),
                    _connector="OR",
                ),
                name="service_point_association_dates_ordered",
            ),
        ),
        migrations.AddConstraint(
            model_name="procedureservicepointassociation",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "verification_state__in",
                        ["current", "needs_reverification", "stale", "disputed", "unknown"],
                    )
                ),
                name="service_point_association_verification_supported",
            ),
        ),
        migrations.AddConstraint(
            model_name="servicepointversion",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("verified_on__isnull", True),
                    ("reverify_on__isnull", True),
                    ("verified_on__lte", models.F("reverify_on")),
                    _connector="OR",
                ),
                name="service_point_version_verification_dates_ordered",
            ),
        ),
        migrations.AddConstraint(
            model_name="procedureservicepointassociation",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("verified_on__isnull", True),
                    ("reverify_on__isnull", True),
                    ("verified_on__lte", models.F("reverify_on")),
                    _connector="OR",
                ),
                name="service_point_association_verification_dates_ordered",
            ),
        ),
        migrations.RunSQL(ROUTING_GUARDS_SQL, reverse_sql=ROUTING_GUARDS_REVERSE_SQL),
    ]
