# Generated by Django 5.2.17 on 2026-09-05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("knowledge", "0009_service_point_routing"),
    ]

    operations = [
        migrations.AlterField(
            model_name="servicepointversion",
            name="effective_from",
            field=models.DateField(),
        ),
    ]
