# Generated by Django 5.2.17 on 2026-09-05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("knowledge", "0010_require_service_point_effective_from"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EvidenceDiscrepancy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("open", "Open"), ("resolved", "Resolved")],
                        default="open",
                        max_length=16,
                    ),
                ),
                (
                    "outcome_state",
                    models.CharField(
                        choices=[
                            ("current", "Current"),
                            ("needs_reverification", "Needs reverification"),
                            ("stale", "Stale"),
                            ("disputed", "Disputed"),
                            ("unknown", "Unknown"),
                        ],
                        default="disputed",
                        max_length=24,
                    ),
                ),
                ("rationale", models.TextField()),
                ("resolution", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "anchor_evidence_link",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="anchored_discrepancies",
                        to="knowledge.evidencelink",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_evidence_discrepancies",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="resolved_evidence_discrepancies",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("status", "created_at", "id"),
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("status__in", ["open", "resolved"])),
                        name="evidence_discrepancy_status_supported",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "outcome_state__in",
                                ["current", "disputed", "needs_reverification", "stale", "unknown"],
                            )
                        ),
                        name="evidence_discrepancy_outcome_supported",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("rationale__regex", ".*[^[:space:]].*")),
                        name="evidence_discrepancy_rationale_nonblank",
                    ),
                    models.CheckConstraint(
                        condition=(
                            models.Q(
                                ("resolved_at__isnull", True),
                                ("resolved_by__isnull", True),
                                ("status", "open"),
                            )
                            | models.Q(
                                ("resolved_at__isnull", False),
                                ("resolved_by__isnull", False),
                                ("status", "resolved"),
                            )
                        ),
                        name="evidence_discrepancy_lifecycle",
                    ),
                    models.CheckConstraint(
                        condition=(
                            ~models.Q(("status", "open"))
                            | models.Q(
                                (
                                    "outcome_state__in",
                                    ["disputed", "needs_reverification", "unknown"],
                                )
                            )
                        ),
                        name="open_discrepancy_is_inconclusive",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="EvidenceReverificationEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "verification_state",
                    models.CharField(
                        choices=[
                            ("current", "Current"),
                            ("needs_reverification", "Needs reverification"),
                            ("stale", "Stale"),
                            ("disputed", "Disputed"),
                            ("unknown", "Unknown"),
                        ],
                        max_length=24,
                    ),
                ),
                ("verified_on", models.DateField()),
                ("reverify_on", models.DateField(blank=True, null=True)),
                ("rationale", models.TextField()),
                ("meaning_changed", models.BooleanField(default=False)),
                ("occurred_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="evidence_reverification_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "anchor_evidence_link",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reverification_events",
                        to="knowledge.evidencelink",
                    ),
                ),
                (
                    "successor_version",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="evidence_change_events",
                        to="knowledge.procedureversion",
                    ),
                ),
            ],
            options={
                "ordering": ("occurred_at", "id"),
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "verification_state__in",
                                ["current", "disputed", "needs_reverification", "stale", "unknown"],
                            )
                        ),
                        name="reverification_state_supported",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("rationale__regex", ".*[^[:space:]].*")),
                        name="reverification_rationale_nonblank",
                    ),
                    models.CheckConstraint(
                        condition=(
                            models.Q(("reverify_on__isnull", True))
                            | models.Q(("verified_on__lte", models.F("reverify_on")))
                        ),
                        name="reverification_dates_ordered",
                    ),
                    models.CheckConstraint(
                        condition=(
                            models.Q(
                                ("meaning_changed", False), ("successor_version__isnull", True)
                            )
                            | models.Q(
                                ("meaning_changed", True), ("successor_version__isnull", False)
                            )
                        ),
                        name="reverification_successor_policy",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="EvidenceDiscrepancyEvidence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "discrepancy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evidence_rows",
                        to="knowledge.evidencediscrepancy",
                    ),
                ),
                (
                    "evidence_link",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="discrepancy_rows",
                        to="knowledge.evidencelink",
                    ),
                ),
            ],
            options={
                "ordering": ("discrepancy_id", "evidence_link_id"),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("discrepancy", "evidence_link"),
                        name="unique_discrepancy_evidence_link",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="EvidenceReverificationEvidence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evidence_rows",
                        to="knowledge.evidencereverificationevent",
                    ),
                ),
                (
                    "evidence_link",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reverification_rows",
                        to="knowledge.evidencelink",
                    ),
                ),
            ],
            options={
                "ordering": ("event_id", "evidence_link_id"),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("event", "evidence_link"),
                        name="unique_reverification_evidence_link",
                    )
                ],
            },
        ),
        migrations.AddField(
            model_name="evidencediscrepancy",
            name="evidence_links",
            field=models.ManyToManyField(
                related_name="discrepancies",
                through="knowledge.EvidenceDiscrepancyEvidence",
                to="knowledge.evidencelink",
            ),
        ),
        migrations.AddField(
            model_name="evidencereverificationevent",
            name="reviewed_evidence_links",
            field=models.ManyToManyField(
                related_name="review_events",
                through="knowledge.EvidenceReverificationEvidence",
                to="knowledge.evidencelink",
            ),
        ),
    ]
