# Generated by Django 5.2.17 on 2026-09-05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("knowledge", "0011_evidence_discrepancy_workflow"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EvidenceDiscrepancyTransition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[("opened", "Opened"), ("resolved", "Resolved")],
                        max_length=16,
                    ),
                ),
                (
                    "verification_state",
                    models.CharField(
                        choices=[
                            ("current", "Current"),
                            ("needs_reverification", "Needs reverification"),
                            ("stale", "Stale"),
                            ("disputed", "Disputed"),
                            ("unknown", "Unknown"),
                        ],
                        max_length=24,
                    ),
                ),
                ("occurred_at", models.DateTimeField()),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="evidence_discrepancy_transitions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "discrepancy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transitions",
                        to="knowledge.evidencediscrepancy",
                    ),
                ),
            ],
            options={"ordering": ("occurred_at", "id")},
        ),
        migrations.AddConstraint(
            model_name="evidencediscrepancytransition",
            constraint=models.UniqueConstraint(
                fields=("discrepancy", "event_type"),
                name="unique_evidence_discrepancy_transition",
            ),
        ),
        migrations.AddConstraint(
            model_name="evidencediscrepancytransition",
            constraint=models.CheckConstraint(
                condition=models.Q(("event_type__in", ["opened", "resolved"])),
                name="evidence_discrepancy_transition_type_supported",
            ),
        ),
        migrations.AddConstraint(
            model_name="evidencediscrepancytransition",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "verification_state__in",
                        ["current", "disputed", "needs_reverification", "stale", "unknown"],
                    )
                ),
                name="evidence_discrepancy_transition_state_supported",
            ),
        ),
    ]
