# Generated by Django 5.2.17 on 2026-09-05

from django.db import migrations, models


_SCENARIO_GUARD_SQL = r"""
CREATE OR REPLACE FUNCTION knowledge_guard_planning_scenario()
RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE
    owner_id bigint;
    owner_state text;
BEGIN
    owner_id := CASE
        WHEN TG_OP = 'DELETE' THEN OLD.procedure_version_id
        ELSE NEW.procedure_version_id
    END;

    IF TG_OP = 'UPDATE' AND OLD.procedure_version_id <> NEW.procedure_version_id THEN
        RAISE EXCEPTION 'planning scenario ownership is immutable';
    END IF;

    SELECT state INTO owner_state
    FROM knowledge_procedureversion
    WHERE id = owner_id;

    IF owner_state IS DISTINCT FROM 'draft' THEN
        RAISE EXCEPTION 'published planning scenarios are immutable acceptance history';
    END IF;

    IF TG_OP = 'DELETE' THEN
        RETURN OLD;
    END IF;
    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS knowledge_guard_planning_scenario_write ON knowledge_planningscenario;
CREATE TRIGGER knowledge_guard_planning_scenario_write
BEFORE INSERT OR UPDATE OR DELETE ON knowledge_planningscenario
FOR EACH ROW EXECUTE FUNCTION knowledge_guard_planning_scenario();
"""

_SCENARIO_GUARD_REVERSE_SQL = r"""
DROP TRIGGER IF EXISTS knowledge_guard_planning_scenario_write ON knowledge_planningscenario;
DROP FUNCTION IF EXISTS knowledge_guard_planning_scenario();
"""


class Migration(migrations.Migration):
    dependencies = [
        ("knowledge", "0012_evidence_discrepancy_transitions"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlanningScenario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=160)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("positive", "Positive"),
                            ("negative", "Negative"),
                            ("unknown", "Unknown"),
                            ("contradictory", "Contradictory"),
                            ("supported_edge", "Supported edge"),
                        ],
                        max_length=24,
                    ),
                ),
                ("evaluation_context", models.JSONField(default=dict)),
                ("source_facts", models.JSONField(blank=True, default=dict)),
                (
                    "expected_result_family",
                    models.CharField(
                        choices=[
                            ("plan", "Plan"),
                            ("next_question", "Next question"),
                            ("inconclusive", "Inconclusive"),
                            ("invalid", "Invalid"),
                        ],
                        max_length=24,
                    ),
                ),
                ("expected_identifiers", models.JSONField(blank=True, default=dict)),
                ("expected_diagnostics", models.JSONField(blank=True, default=list)),
                ("behavior_signature", models.CharField(editable=False, max_length=64)),
                (
                    "procedure_version",
                    models.ForeignKey(
                        on_delete=models.CASCADE,
                        related_name="planning_scenarios",
                        to="knowledge.procedureversion",
                    ),
                ),
            ],
            options={
                "ordering": ("procedure_version_id", "kind", "name", "id"),
            },
        ),
        migrations.AddConstraint(
            model_name="planningscenario",
            constraint=models.UniqueConstraint(
                fields=("procedure_version", "name"),
                name="unique_planning_scenario_name_per_version",
            ),
        ),
        migrations.AddConstraint(
            model_name="planningscenario",
            constraint=models.CheckConstraint(
                condition=models.Q(("name__regex", ".*[^[:space:]].*")),
                name="planning_scenario_name_nonblank",
            ),
        ),
        migrations.AddConstraint(
            model_name="planningscenario",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "kind__in",
                        [
                            "positive",
                            "negative",
                            "unknown",
                            "contradictory",
                            "supported_edge",
                        ],
                    )
                ),
                name="planning_scenario_kind_supported",
            ),
        ),
        migrations.AddConstraint(
            model_name="planningscenario",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "expected_result_family__in",
                        ["plan", "next_question", "inconclusive", "invalid"],
                    )
                ),
                name="planning_scenario_result_supported",
            ),
        ),
        migrations.RunSQL(
            sql=_SCENARIO_GUARD_SQL,
            reverse_sql=_SCENARIO_GUARD_REVERSE_SQL,
        ),
    ]
