# Generated by Django 5.2.17 on 2026-09-06
# ruff: noqa: I001

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


_REVIEW_GUARD_SQL = r"""
CREATE OR REPLACE FUNCTION knowledge_guard_procedure_version_review_policy()
RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE
    owner_id bigint;
    owner_state text;
BEGIN
    owner_id := CASE
        WHEN TG_OP = 'DELETE' THEN OLD.procedure_version_id
        ELSE NEW.procedure_version_id
    END;

    IF TG_OP = 'UPDATE' AND OLD.procedure_version_id <> NEW.procedure_version_id THEN
        RAISE EXCEPTION 'review policy ownership is immutable';
    END IF;

    SELECT state INTO owner_state
    FROM knowledge_procedureversion
    WHERE id = owner_id;

    IF owner_state IS DISTINCT FROM 'draft' THEN
        RAISE EXCEPTION 'review policy is editable only for draft versions';
    END IF;

    IF TG_OP = 'DELETE' THEN
        RETURN OLD;
    END IF;
    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS knowledge_guard_procedure_version_review_policy_write
ON knowledge_procedureversionreviewpolicy;
CREATE TRIGGER knowledge_guard_procedure_version_review_policy_write
BEFORE INSERT OR UPDATE OR DELETE ON knowledge_procedureversionreviewpolicy
FOR EACH ROW EXECUTE FUNCTION knowledge_guard_procedure_version_review_policy();

CREATE OR REPLACE FUNCTION knowledge_guard_procedure_version_review_approval()
RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE
    owner_state text;
BEGIN
    IF TG_OP <> 'INSERT' THEN
        RAISE EXCEPTION 'procedure version review approvals are immutable';
    END IF;

    SELECT state INTO owner_state
    FROM knowledge_procedureversion
    WHERE id = NEW.procedure_version_id;

    IF owner_state IS DISTINCT FROM 'draft' THEN
        RAISE EXCEPTION 'review approvals may be recorded only for draft versions';
    END IF;
    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS knowledge_guard_procedure_version_review_approval_write
ON knowledge_procedureversionreviewapproval;
CREATE TRIGGER knowledge_guard_procedure_version_review_approval_write
BEFORE INSERT OR UPDATE OR DELETE ON knowledge_procedureversionreviewapproval
FOR EACH ROW EXECUTE FUNCTION knowledge_guard_procedure_version_review_approval();

CREATE OR REPLACE FUNCTION knowledge_guard_procedure_version_audit_approval()
RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE
    lifecycle text;
BEGIN
    lifecycle := current_setting('bardi.procedure_version_lifecycle', true);
    IF TG_OP = 'INSERT' AND lifecycle = 'publish' THEN
        RETURN NEW;
    END IF;
    RAISE EXCEPTION 'publication approval audit rows are immutable lifecycle records';
END;
$$;

DROP TRIGGER IF EXISTS knowledge_guard_procedure_version_audit_approval_write
ON knowledge_procedureversionauditapproval;
CREATE TRIGGER knowledge_guard_procedure_version_audit_approval_write
BEFORE INSERT OR UPDATE OR DELETE ON knowledge_procedureversionauditapproval
FOR EACH ROW EXECUTE FUNCTION knowledge_guard_procedure_version_audit_approval();

CREATE OR REPLACE FUNCTION knowledge_capture_procedure_version_review_approvals()
RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE
    review_signature text;
BEGIN
    IF NEW.event_type <> 'published' THEN
        RETURN NEW;
    END IF;

    review_signature := current_setting('bardi.procedure_version_review_signature', true);
    IF review_signature IS NULL OR review_signature = '' THEN
        RETURN NEW;
    END IF;

    INSERT INTO knowledge_procedureversionauditapproval
        (
            audit_event_id,
            approval_id,
            actor_id,
            approval_kind,
            dimension,
            specialist_risk,
            approved_at
        )
    SELECT
        NEW.id,
        approval.id,
        approval.reviewer_id,
        approval.approval_kind,
        approval.dimension,
        approval.specialist_risk,
        approval.approved_at
    FROM knowledge_procedureversionreviewapproval AS approval
    INNER JOIN knowledge_procedureversionreviewpolicy AS policy
        ON policy.procedure_version_id = NEW.version_id
    WHERE approval.procedure_version_id = NEW.version_id
      AND approval.reviewed_signature = review_signature
      AND approval.reviewer_id <> policy.author_id
      AND approval.reviewer_id <> NEW.actor_id;

    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS knowledge_capture_procedure_version_review_approvals_insert
ON knowledge_procedureversionauditevent;
CREATE TRIGGER knowledge_capture_procedure_version_review_approvals_insert
AFTER INSERT ON knowledge_procedureversionauditevent
FOR EACH ROW EXECUTE FUNCTION knowledge_capture_procedure_version_review_approvals();
"""

_REVIEW_GUARD_REVERSE_SQL = r"""
DROP TRIGGER IF EXISTS knowledge_capture_procedure_version_review_approvals_insert
ON knowledge_procedureversionauditevent;
DROP FUNCTION IF EXISTS knowledge_capture_procedure_version_review_approvals();
DROP TRIGGER IF EXISTS knowledge_guard_procedure_version_audit_approval_write
ON knowledge_procedureversionauditapproval;
DROP FUNCTION IF EXISTS knowledge_guard_procedure_version_audit_approval();
DROP TRIGGER IF EXISTS knowledge_guard_procedure_version_review_approval_write
ON knowledge_procedureversionreviewapproval;
DROP FUNCTION IF EXISTS knowledge_guard_procedure_version_review_approval();
DROP TRIGGER IF EXISTS knowledge_guard_procedure_version_review_policy_write
ON knowledge_procedureversionreviewpolicy;
DROP FUNCTION IF EXISTS knowledge_guard_procedure_version_review_policy();
"""


class Migration(migrations.Migration):
    dependencies = [
        ("knowledge", "0013_planning_scenarios"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProcedureVersionReviewPolicy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("legal_risk", models.BooleanField(default=False)),
                ("military_risk", models.BooleanField(default=False)),
                ("custody_guardianship_risk", models.BooleanField(default=False)),
                ("contested_identity_risk", models.BooleanField(default=False)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="authored_review_policies",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "procedure_version",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="review_policy",
                        to="knowledge.procedureversion",
                    ),
                ),
            ],
            options={
                "ordering": ("procedure_version__semantic_id",),
            },
        ),
        migrations.CreateModel(
            name="ProcedureVersionReviewApproval",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "approval_kind",
                    models.CharField(
                        choices=[
                            ("dimension", "Review dimension"),
                            ("specialist", "Specialist"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "dimension",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("evidence_source", "Evidence/source"),
                            ("rule_logic", "Rule/logic"),
                            ("scenario_behavior", "Scenario/behavior"),
                            ("bilingual_semantic", "Arabic/English semantic"),
                            ("discrepancy", "Discrepancy"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "specialist_risk",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("legal", "Legal"),
                            ("military", "Military"),
                            ("custody_guardianship", "Custody/guardianship"),
                            ("contested_identity", "Contested identity"),
                        ],
                        max_length=32,
                    ),
                ),
                ("reviewed_signature", models.CharField(max_length=64)),
                ("approved_at", models.DateTimeField()),
                (
                    "procedure_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="review_approvals",
                        to="knowledge.procedureversion",
                    ),
                ),
                (
                    "reviewer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="procedure_version_review_approvals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("approved_at", "id"),
                "permissions": [
                    (
                        "review_procedureversion",
                        "Can approve Procedure Version review dimensions",
                    ),
                    ("specialist_approve_legal", "Can approve high-risk legal material"),
                    (
                        "specialist_approve_military",
                        "Can approve high-risk military material",
                    ),
                    (
                        "specialist_approve_custody_guardianship",
                        "Can approve high-risk custody/guardianship material",
                    ),
                    (
                        "specialist_approve_contested_identity",
                        "Can approve high-risk contested-identity material",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ProcedureVersionAuditApproval",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "approval_kind",
                    models.CharField(
                        choices=[
                            ("dimension", "Review dimension"),
                            ("specialist", "Specialist"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "dimension",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("evidence_source", "Evidence/source"),
                            ("rule_logic", "Rule/logic"),
                            ("scenario_behavior", "Scenario/behavior"),
                            ("bilingual_semantic", "Arabic/English semantic"),
                            ("discrepancy", "Discrepancy"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "specialist_risk",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("legal", "Legal"),
                            ("military", "Military"),
                            ("custody_guardianship", "Custody/guardianship"),
                            ("contested_identity", "Contested identity"),
                        ],
                        max_length=32,
                    ),
                ),
                ("approved_at", models.DateTimeField()),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="procedure_version_audit_approvals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "approval",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="publication_audit_rows",
                        to="knowledge.procedureversionreviewapproval",
                    ),
                ),
                (
                    "audit_event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="approvals",
                        to="knowledge.procedureversionauditevent",
                    ),
                ),
            ],
            options={
                "ordering": (
                    "audit_event_id",
                    "approval_kind",
                    "dimension",
                    "specialist_risk",
                    "id",
                ),
            },
        ),
        migrations.AddConstraint(
            model_name="procedureversionreviewapproval",
            constraint=models.CheckConstraint(
                condition=models.Q(("approval_kind__in", ["dimension", "specialist"])),
                name="review_approval_kind_supported",
            ),
        ),
        migrations.AddConstraint(
            model_name="procedureversionreviewapproval",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("approval_kind", "dimension"),
                        (
                            "dimension__in",
                            list(
                                (
                                    "evidence_source",
                                    "rule_logic",
                                    "scenario_behavior",
                                    "bilingual_semantic",
                                    "discrepancy",
                                )
                            ),
                        ),
                        ("specialist_risk", ""),
                    ),
                    models.Q(
                        ("approval_kind", "specialist"),
                        ("dimension", ""),
                        (
                            "specialist_risk__in",
                            list(
                                (
                                    "legal",
                                    "military",
                                    "custody_guardianship",
                                    "contested_identity",
                                )
                            ),
                        ),
                    ),
                    _connector="OR",
                ),
                name="review_approval_scope_shape",
            ),
        ),
        migrations.AddConstraint(
            model_name="procedureversionreviewapproval",
            constraint=models.CheckConstraint(
                condition=models.Q(("reviewed_signature__regex", "^[0-9a-f]{64}$")),
                name="review_approval_signature_sha256",
            ),
        ),
        migrations.AddConstraint(
            model_name="procedureversionreviewapproval",
            constraint=models.UniqueConstraint(
                condition=models.Q(("approval_kind", "dimension")),
                fields=("procedure_version", "dimension", "reviewer", "reviewed_signature"),
                name="unique_dimension_review_approval",
            ),
        ),
        migrations.AddConstraint(
            model_name="procedureversionreviewapproval",
            constraint=models.UniqueConstraint(
                condition=models.Q(("approval_kind", "specialist")),
                fields=(
                    "procedure_version",
                    "specialist_risk",
                    "reviewer",
                    "reviewed_signature",
                ),
                name="unique_specialist_review_approval",
            ),
        ),
        migrations.AddConstraint(
            model_name="procedureversionauditapproval",
            constraint=models.UniqueConstraint(
                fields=("audit_event", "approval"),
                name="unique_publication_audit_approval",
            ),
        ),
        migrations.RunSQL(sql=_REVIEW_GUARD_SQL, reverse_sql=_REVIEW_GUARD_REVERSE_SQL),
    ]
