# Generated by Django 5.2.17 on 2026-09-06 00:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("knowledge", "0014_procedure_version_reviews"),
    ]

    operations = [
        migrations.AddField(
            model_name="evidencelink",
            name="semantic_id",
            field=models.CharField(blank=True, default="", max_length=128),
        ),
        migrations.AddConstraint(
            model_name="evidencelink",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("checklist_item__isnull", False), models.Q(("semantic_id", ""), _negated=True)
                ),
                fields=("checklist_item", "semantic_id"),
                name="unique_evidence_id_checklist_owner",
            ),
        ),
        migrations.AddConstraint(
            model_name="evidencelink",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("step__isnull", False), models.Q(("semantic_id", ""), _negated=True)
                ),
                fields=("step", "semantic_id"),
                name="unique_evidence_id_step_owner",
            ),
        ),
        migrations.AddConstraint(
            model_name="evidencelink",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("warning__isnull", False), models.Q(("semantic_id", ""), _negated=True)
                ),
                fields=("warning", "semantic_id"),
                name="unique_evidence_id_warning_owner",
            ),
        ),
        migrations.AddConstraint(
            model_name="evidencelink",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("fee__isnull", False), models.Q(("semantic_id", ""), _negated=True)
                ),
                fields=("fee", "semantic_id"),
                name="unique_evidence_id_fee_owner",
            ),
        ),
        migrations.AddConstraint(
            model_name="evidencelink",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("eligibility_basis__isnull", False),
                    models.Q(("semantic_id", ""), _negated=True),
                ),
                fields=("eligibility_basis", "semantic_id"),
                name="unique_evidence_id_basis_owner",
            ),
        ),
        migrations.AddConstraint(
            model_name="evidencelink",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("procedure_dependency__isnull", False),
                    models.Q(("semantic_id", ""), _negated=True),
                ),
                fields=("procedure_dependency", "semantic_id"),
                name="unique_evidence_id_dependency_owner",
            ),
        ),
        migrations.AddConstraint(
            model_name="evidencelink",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("service_point_version__isnull", False),
                    models.Q(("semantic_id", ""), _negated=True),
                ),
                fields=("service_point_version", "semantic_id"),
                name="unique_evidence_id_point_version_owner",
            ),
        ),
        migrations.AddConstraint(
            model_name="evidencelink",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("procedure_service_point_association__isnull", False),
                    models.Q(("semantic_id", ""), _negated=True),
                ),
                fields=("procedure_service_point_association", "semantic_id"),
                name="unique_evidence_id_point_association_owner",
            ),
        ),
    ]
