# Generated by Django 5.2.17 on 2026-09-06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("knowledge", "0015_evidence_link_semantic_id"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="evidencelink",
            constraint=models.CheckConstraint(
                condition=models.Q(("semantic_id", ""))
                | models.Q(("semantic_id__regex", r"\S")),
                name="evidence_semantic_id_blank_or_nonblank",
            ),
        ),
    ]
