# Generated by Django 5.2.17 on 2026-09-10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("knowledge", "0016_evidence_semantic_id_nonblank"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="eligibilitybasis",
            options={
                "ordering": (
                    "procedure_version_id",
                    "display_order",
                    "semantic_id",
                )
            },
        ),
    ]
