# Generated by Django 5.2.17 on 2026-09-16 02:01

from importlib import import_module

from django.db import migrations, models

_CAPTURE_SQL = import_module(
    "knowledge.migrations.0014_procedure_version_reviews"
)._REVIEW_GUARD_SQL.split(
    "CREATE OR REPLACE FUNCTION knowledge_capture_procedure_version_review_approvals()"
)[1]
_RESTORE_CAPTURE_SQL = (
    "CREATE OR REPLACE FUNCTION knowledge_capture_procedure_version_review_approvals()"
    + _CAPTURE_SQL
)


class Migration(migrations.Migration):
    dependencies = [
        ("knowledge", "0016_evidence_semantic_id_nonblank"),
    ]

    operations = [
        migrations.RunSQL(
            "DROP TRIGGER IF EXISTS knowledge_capture_procedure_version_review_approvals_insert "
            "ON knowledge_procedureversionauditevent; "
            "DROP FUNCTION IF EXISTS knowledge_capture_procedure_version_review_approvals();",
            reverse_sql=_RESTORE_CAPTURE_SQL,
        ),
        migrations.AddField(
            model_name="procedureversionauditevent",
            name="review_mode",
            field=models.CharField(
                blank=True,
                choices=[("solo", "Solo"), ("independent", "Independent")],
                max_length=16,
                null=True,
            ),
        ),
    ]
