/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/planning": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Planning */
        post: operations["api_api_planning"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/services": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Services */
        get: operations["api_api_services"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AnswerDefinitionResponse */
        AnswerDefinitionResponse: {
            /** Enum Options */
            enum_options: string[];
            /** Key */
            key: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "enum" | "integer" | "boolean" | "date" | "string";
            /** Minimum */
            minimum: number | null;
        };
        /** ChecklistItemResponse */
        ChecklistItemResponse: {
            /**
             * Classification
             * @enum {string}
             */
            classification: "official_requirement" | "practical_preparation";
            /** Classification Label */
            classification_label: string;
            /** Copy Quantity */
            copy_quantity: number;
            /** Document Type Id */
            document_type_id: string | null;
            freshness: components["schemas"]["FreshnessResponse"];
            /** Id */
            id: string;
            /** Original Quantity */
            original_quantity: number;
            /** Quantity */
            quantity: number;
            /**
             * Scope
             * @enum {string}
             */
            scope: "procedure" | "eligibility_basis";
            /** Sources */
            sources: components["schemas"]["GuidanceSourceResponse"][];
            /** Text */
            text: string;
        };
        /** DiagnosticResponse */
        DiagnosticResponse: {
            /** Code */
            code: string;
            /** Path */
            path: (string | number)[];
        };
        /** EligibilityBasisResponse */
        EligibilityBasisResponse: {
            /** Checklist Item Ids */
            checklist_item_ids: string[];
            freshness: components["schemas"]["FreshnessResponse"];
            /** Id */
            id: string;
            /** Sources */
            sources: components["schemas"]["GuidanceSourceResponse"][];
            /** Step Ids */
            step_ids: string[];
            /** Text */
            text: string;
        };
        /** EvaluationContext */
        EvaluationContext: {
            /**
             * Evaluation Date
             * Format: date
             */
            evaluation_date: string;
        };
        /** FeeResponse */
        FeeResponse: {
            /** Amount */
            amount: number | null;
            /** Currency */
            currency: string;
            /** Current Value Unknown */
            current_value_unknown: boolean;
            /** Fee Type */
            fee_type: string;
            freshness: components["schemas"]["FreshnessResponse"];
            /** Id */
            id: string;
            /** Maximum Amount */
            maximum_amount: number | null;
            /** Minimum Amount */
            minimum_amount: number | null;
            /** Sources */
            sources: components["schemas"]["GuidanceSourceResponse"][];
            /** Text */
            text: string;
            /**
             * Value State
             * @enum {string}
             */
            value_state: "known" | "range" | "unknown" | "unverified";
        };
        /** FreshnessResponse */
        FreshnessResponse: {
            /** Reverify On */
            reverify_on: string | null;
            /**
             * State
             * @enum {string}
             */
            state: "current" | "needs_reverification" | "stale" | "disputed" | "unknown";
            /** Verified On */
            verified_on: string | null;
        };
        /** GuidanceSourceResponse */
        GuidanceSourceResponse: {
            /** Authority Id */
            authority_id: string;
            /**
             * Classification
             * @enum {string}
             */
            classification: "official" | "field_report" | "secondary";
            /** Id */
            id: string;
            /** Locator */
            locator: string;
            /**
             * Retrieved On
             * Format: date
             */
            retrieved_on: string;
            /** Title */
            title: string;
        };
        /** InconclusiveResponse */
        InconclusiveResponse: {
            /** Message */
            message: string;
            /** Reason */
            reason: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "inconclusive";
        };
        /** InvalidResponse */
        InvalidResponse: {
            /** Diagnostics */
            diagnostics: components["schemas"]["DiagnosticResponse"][];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "invalid";
        };
        /** LocalizedTitleResponse */
        LocalizedTitleResponse: {
            /** Ar */
            ar: string;
            /** En */
            en: string;
        };
        /** NavigationResponse */
        NavigationResponse: {
            /** Services */
            services: components["schemas"]["ServiceNavigationItem"][];
        };
        /** NextQuestionResponse */
        NextQuestionResponse: {
            question: components["schemas"]["QuestionResponse"];
            /** Service Id */
            service_id: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "next_question";
        };
        /** PlanResponse */
        PlanResponse: {
            /** Checklist Items */
            checklist_items: components["schemas"]["ChecklistItemResponse"][];
            /** Dependencies */
            dependencies: components["schemas"]["ProcedureDependencyResponse"][];
            /** Eligibility Bases */
            eligibility_bases: components["schemas"]["EligibilityBasisResponse"][];
            /** Fees */
            fees: components["schemas"]["FeeResponse"][];
            /** Inconclusive Basis Ids */
            inconclusive_basis_ids: string[];
            /** Inconclusive Sections */
            inconclusive_sections: ("checklist_items" | "steps")[];
            /** Procedure Id */
            procedure_id: string;
            /** Procedure Version Id */
            procedure_version_id: string;
            routing: components["schemas"]["RoutingResponse"];
            /** Service Id */
            service_id: string;
            /** Steps */
            steps: components["schemas"]["StepResponse"][];
            /** Title */
            title: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "plan";
            /** Warnings */
            warnings: components["schemas"]["WarningResponse"][];
        };
        /** PlanningRequest */
        PlanningRequest: {
            evaluation_context: components["schemas"]["EvaluationContext"];
            /** Facts */
            facts: {
                [key: string]: components["schemas"]["TransportValue"];
            };
            /**
             * Locale
             * @enum {string}
             */
            locale: "ar" | "en";
            /** Service Id */
            service_id: string;
        };
        PlanningResponse: components["schemas"]["NextQuestionResponse"] | components["schemas"]["PlanResponse"] | components["schemas"]["InconclusiveResponse"] | components["schemas"]["InvalidResponse"];
        /** ProcedureDependencyResponse */
        ProcedureDependencyResponse: {
            freshness: components["schemas"]["FreshnessResponse"];
            /** Id */
            id: string;
            /**
             * Relation
             * @constant
             */
            relation: "blocking_prerequisite";
            /** Sources */
            sources: components["schemas"]["GuidanceSourceResponse"][];
            /**
             * Status
             * @enum {string}
             */
            status: "satisfied" | "blocking" | "unsupported_target" | "inconclusive";
            /** Target Procedure */
            target_procedure: string;
            /** Target Procedure Id */
            target_procedure_id: string;
            /** Target Procedure Version Id */
            target_procedure_version_id: string | null;
            /** Text */
            text: string;
        };
        /** QuestionResponse */
        QuestionResponse: {
            /** Answers */
            answers: components["schemas"]["AnswerDefinitionResponse"][];
            /** Id */
            id: string;
            /** Text */
            text: string;
        };
        /** RoutingResponse */
        RoutingResponse: {
            /** Destinations */
            destinations: components["schemas"]["ServicePointResponse"][];
            /**
             * Status
             * @enum {string}
             */
            status: "resolved" | "partially_resolved" | "unresolved";
            /** Verification Sources */
            verification_sources: components["schemas"]["GuidanceSourceResponse"][];
        };
        /** ServiceNavigationItem */
        ServiceNavigationItem: {
            /** Id */
            id: string;
            title: components["schemas"]["LocalizedTitleResponse"];
        };
        /** ServicePointResponse */
        ServicePointResponse: {
            /** Address */
            address: string;
            /** Association Id */
            association_id: string;
            /**
             * Availability
             * @enum {string}
             */
            availability: "available" | "unknown";
            /** Effective From */
            effective_from: string | null;
            /** Effective To */
            effective_to: string | null;
            /** Name */
            name: string;
            /** Service Point Id */
            service_point_id: string;
            /** Service Point Version Id */
            service_point_version_id: string;
            /** Sources */
            sources: components["schemas"]["GuidanceSourceResponse"][];
        };
        /** StepResponse */
        StepResponse: {
            freshness: components["schemas"]["FreshnessResponse"];
            /** Id */
            id: string;
            /** Phase */
            phase: string;
            /** Sources */
            sources: components["schemas"]["GuidanceSourceResponse"][];
            /** Text */
            text: string;
        };
        TransportValue: boolean | number | string | null;
        /** WarningResponse */
        WarningResponse: {
            freshness: components["schemas"]["FreshnessResponse"];
            /** Id */
            id: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "administrative" | "product";
            /**
             * Role
             * @enum {string}
             */
            role: "general" | "regeneration" | "limitation";
            /**
             * Severity
             * @enum {string}
             */
            severity: "info" | "important";
            /** Sources */
            sources: components["schemas"]["GuidanceSourceResponse"][];
            /** Text */
            text: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    api_api_planning: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PlanningRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanningResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvalidResponse"];
                };
            };
            /** @description Content Too Large */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvalidResponse"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvalidResponse"];
                };
            };
            /** @description Too Many Requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvalidResponse"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvalidResponse"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InconclusiveResponse"];
                };
            };
        };
    };
    api_api_services: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NavigationResponse"];
                };
            };
            /** @description Too Many Requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvalidResponse"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvalidResponse"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InconclusiveResponse"];
                };
            };
        };
    };
}
