"""Public framework-independent planning domain."""

from .catalog import (
    ContradictionSnapshot,
    KnowledgeSnapshot,
    LocalizedText,
    ProcedureCandidateSnapshot,
    QuestionSnapshot,
    ServiceSnapshot,
)
from .diagnostics import DiagnosticPath, DiagnosticPathSegment, ValidationDiagnostic
from .evaluator import Evaluation, EvaluationTrace, TruthValue, evaluate
from .facts import (
    FACT_DEFINITIONS,
    FactDefinition,
    FactKind,
    FactValidationResult,
    FactValue,
    PreparedFacts,
    validate_submitted_facts,
    value_matches_definition,
)
from .rules import (
    BOOLEAN_OPERATORS,
    LEAF_OPERATORS,
    MAX_IN_OPERANDS,
    MAX_RULE_NODES,
    SUPPORTED_OPERATORS,
    BooleanOperator,
    LeafOperator,
    Predicate,
    RuleOperator,
    RuleValidationResult,
    serialize_rule_v1,
    validate_rule_v1,
)
from .selection import (
    CandidateEvaluation,
    ProcedureSelected,
    SelectionConfigurationDefect,
    SelectionInconclusive,
    SelectionOutcome,
    SelectionQuestion,
    SelectionUnsupported,
    select_procedure,
)

__all__ = (
    "BOOLEAN_OPERATORS",
    "FACT_DEFINITIONS",
    "LEAF_OPERATORS",
    "MAX_IN_OPERANDS",
    "MAX_RULE_NODES",
    "SUPPORTED_OPERATORS",
    "BooleanOperator",
    "CandidateEvaluation",
    "ContradictionSnapshot",
    "DiagnosticPath",
    "DiagnosticPathSegment",
    "Evaluation",
    "EvaluationTrace",
    "FactDefinition",
    "FactKind",
    "FactValidationResult",
    "FactValue",
    "KnowledgeSnapshot",
    "LeafOperator",
    "LocalizedText",
    "PreparedFacts",
    "ProcedureCandidateSnapshot",
    "ProcedureSelected",
    "QuestionSnapshot",
    "Predicate",
    "RuleOperator",
    "RuleValidationResult",
    "SelectionConfigurationDefect",
    "SelectionInconclusive",
    "SelectionOutcome",
    "SelectionQuestion",
    "SelectionUnsupported",
    "ServiceSnapshot",
    "TruthValue",
    "ValidationDiagnostic",
    "evaluate",
    "select_procedure",
    "serialize_rule_v1",
    "validate_rule_v1",
    "validate_submitted_facts",
    "value_matches_definition",
)
