import type { Locale } from "@/api/contract";

const en = {
  privacySummary: "Your answers and privacy",
  privacy: "Your submitted answers stay in this tab’s session storage and are sent to Bardi only to prepare guidance, not to save a server case. Browsers may restore tabs. On a shared device, clear your answers here before leaving.",
  restored: "Your answers from this tab are back. We’ll check them again for the selected date.",
  discarded: "The previous tab case could not be used for this service. We’ve removed it so you can start afresh.",
  memory: "Tab storage isn’t available. You can continue here, but changes may not survive refresh. On a shared device, also clear this site’s browser data if you used it before.",
  clear_failed: "Answers and guidance were cleared from this page, but browser storage could not be cleared. Clear this site’s browser data before leaving a shared device.",
  date: "Guidance date",
  dateHint: "Gregorian calendar. You can choose a past date; regenerate for today before acting.",
  useDate: "Use this date",
  today: "Regenerate for today",
  dateEditing: "Apply the date to continue",
  dateEditingHint: "Previous guidance is hidden until you check your answers for the selected date.",
  dateError: "Enter a real Gregorian date in YYYY-MM-DD format, from year 0001 to 9999.",
  loading: "Checking your answers…",
  javascript: "The questionnaire needs JavaScript.",
  javascriptRecovery: "Enable JavaScript and reload this page to continue.",
  backToService: "Back to the service introduction",
  continue: "Continue",
  multiHint: "Answer what you know. You can leave a field unanswered; we may ask for it again. Nothing is selected for you.",
  omit: "Leave unanswered",
  integerHint: "Use whole numbers, with digits 0–9.",
  dateFieldHint: "Gregorian date (YYYY-MM-DD).",
  stringHint: "Up to 2,048 characters. Only enter the information asked for.",
  minimum: "Minimum:",
  errors: "Check your answer",
  boolean: "Choose Yes or No.",
  enum: "Choose one of the available answers.",
  integer: "Enter a whole number between −9007199254740991 and 9007199254740991, using digits 0–9. Do not use decimals or exponent notation.",
  minimumError: "Enter a whole number at or above the minimum shown.",
  string: "Use no more than 2,048 characters.",
  required: "Answer at least one field to continue. An unanswered field is not treated as No.",
  unchanged: "Answer a missing field or change an answer to continue. If you cannot answer, you can review your earlier answers or clear this case.",
  limits: "This case has reached the supported answer limit. Review your earlier answers or clear this case to start again.",
  review: "Review or change answers",
  reviewHint: "Changing an answer removes that answer and every answer after it. We’ll then ask the next relevant question again.",
  change: "Change answer",
  emptyValue: "Empty text",
  clear: "Clear answers and start again",
  clearTitle: "Clear this case?",
  clearHint: "This removes this tab’s Bardi answers and the guidance on this page. It does not clear printed or downloaded copies.",
  confirmClear: "Yes, clear answers",
  cancelClear: "Keep my answers",
  cleared: "Your case is cleared",
  clearedHint: "Start again when you’re ready. No previous answers will be sent.",
  start: "Start again",
  retry: "Try again with these answers",
  network: "We couldn’t connect. Check your connection, then try again. Your submitted answers are still here.",
  unavailable: "Bardi is temporarily unavailable. Your submitted answers are still here; try again later.",
  rate_limited: "There have been too many requests. Your submitted answers are still here. Wait before trying again.",
  unexpected_response: "We couldn’t safely read the response. Your submitted answers are still here. Try again later.",
  failure: "We couldn’t continue",
  wait: "You can try again in",
  seconds: "seconds.",
  inconclusive: "We can’t prepare reliable guidance yet",
  inconclusiveHint: "This is not a decision about your application. Review your answers, try another date, or try again later. We won’t choose a closest match.",
  invalid: "Some information needs checking",
  invalidHint: "Check the answers listed below. Correcting them removes the earliest affected answer and everything after it.",
  invalidGeneral: "We couldn’t use this request. Check the date and your answers, then try again. If it still doesn’t work, clear this case or come back later.",
  contradictory: "Some answers conflict with each other. Check them rather than choosing an answer just to continue.",
  correct: "Correct these answers",
  correctDate: "Correct the date",
  configuration: "We can’t continue with this question",
  configurationHint: "The service returned a question that cannot safely advance this case. Your answers have not been changed. Review them, try again later, or clear this case. We won’t guess the next question.",
  planReady: "Your preparation guidance",
  print: "Print guidance",
  printHint: "Printing uses your browser. Printed or saved copies may contain personal information; keep them safe.",
};
type Copy = { [K in keyof typeof en]: string };
const ar: Copy = {
  privacySummary: "إجاباتك وخصوصيتك",
  privacy: "إجاباتك اللي بتبعتها بتفضل في تخزين جلسة التبويب ده، وبتتبعت لبردي عشان نجهّز الإرشادات بس، مش عشان نحفظ ملف على الخادم. المتصفح ممكن يرجّع التبويبات. لو الجهاز مشترك، امسح إجاباتك من هنا قبل ما تمشي.",
  restored: "رجّعنا إجاباتك من التبويب ده. هنراجعها تاني على التاريخ اللي اخترته.",
  discarded: "الحالة السابقة في التبويب مش مناسبة للخدمة دي أو ما قدرناش نقرأها. مسحناها عشان تبدأ من جديد.",
  memory: "تخزين التبويب مش متاح. تقدر تكمّل هنا، بس التغييرات ممكن تضيع مع تحديث الصفحة. لو الجهاز مشترك واستخدمته قبل كده، امسح كمان بيانات الموقع من المتصفح.",
  clear_failed: "مسحنا الإجابات والإرشادات من الصفحة، بس ما قدرناش نمسح تخزين المتصفح. امسح بيانات الموقع من المتصفح قبل ما تسيب جهاز مشترك.",
  date: "تاريخ الإرشادات",
  dateHint: "بالتقويم الميلادي. تقدر تختار تاريخ سابق؛ جدّد الإرشادات بتاريخ النهارده قبل ما تتحرك.",
  useDate: "استخدم التاريخ ده",
  today: "جدّد بتاريخ النهارده",
  dateEditing: "طبّق التاريخ عشان تكمّل",
  dateEditingHint: "خبّينا الإرشادات السابقة لحد ما نراجع إجاباتك على التاريخ اللي اخترته.",
  dateError: "اكتب تاريخ ميلادي صحيح بصيغة YYYY-MM-DD، من سنة 0001 لحد 9999.",
  loading: "بنراجع إجاباتك…",
  javascript: "الأسئلة محتاجة JavaScript.",
  javascriptRecovery: "فعّل JavaScript وحدّث الصفحة عشان تكمّل.",
  backToService: "ارجع لتعريف الخدمة",
  continue: "كمّل",
  multiHint: "جاوب على اللي تعرفه. تقدر تسيب خانة من غير إجابة، وممكن نسألك عنها تاني. مفيش إجابة متحددة بدلًا منك.",
  omit: "سيبها من غير إجابة",
  integerHint: "استخدم عدد صحيح بالأرقام 0–9.",
  dateFieldHint: "تاريخ ميلادي (YYYY-MM-DD).",
  stringHint: "لحد ٢٬٠٤٨ حرف. اكتب المعلومة المطلوبة بس.",
  minimum: "أقل عدد:",
  errors: "راجع إجابتك",
  boolean: "اختار أيوه أو لأ.",
  enum: "اختار إجابة من الاختيارات الموجودة.",
  integer: "اكتب عدد صحيح بين −9007199254740991 و9007199254740991 بالأرقام 0–9، من غير كسور أو صيغة أسّية.",
  minimumError: "اكتب عدد صحيح يساوي أقل عدد موضح أو أكبر منه.",
  string: "استخدم ٢٬٠٤٨ حرف أو أقل.",
  required: "جاوب على خانة واحدة على الأقل عشان تكمّل. الخانة اللي من غير إجابة مش معناها لأ.",
  unchanged: "جاوب على خانة ناقصة أو غيّر إجابة عشان تكمّل. لو مش عارف تجاوب، تقدر تراجع إجاباتك السابقة أو تمسح الحالة.",
  limits: "وصلنا لحد الإجابات المدعوم للحالة دي. راجع إجاباتك السابقة أو امسح الحالة وابدأ من جديد.",
  review: "راجع أو غيّر إجاباتك",
  reviewHint: "تغيير إجابة بيمسحها هي وكل الإجابات اللي بعدها. بعدها هنسألك السؤال المناسب من جديد.",
  change: "غيّر الإجابة",
  emptyValue: "نص فارغ",
  clear: "امسح الإجابات وابدأ من جديد",
  clearTitle: "نمسح الحالة دي؟",
  clearHint: "ده بيمسح إجابات بردي في التبويب ده والإرشادات من الصفحة. مش بيمسح نسخ مطبوعة أو منزّلة.",
  confirmClear: "أيوه، امسح الإجابات",
  cancelClear: "خلّي إجاباتي",
  cleared: "مسحنا الحالة",
  clearedHint: "ابدأ من جديد لما تكون جاهز. مش هنبعت أي إجابات سابقة.",
  start: "ابدأ من جديد",
  retry: "جرّب تاني بنفس الإجابات",
  network: "ما قدرناش نتصل. راجع اتصالك بالإنترنت وجرّب تاني. إجاباتك اللي بعتها لسه موجودة هنا.",
  unavailable: "بردي مش متاح مؤقتًا. إجاباتك اللي بعتها لسه موجودة هنا؛ جرّب تاني بعد شوية.",
  rate_limited: "في طلبات كتير اتبعتت. إجاباتك اللي بعتها لسه موجودة هنا. استنى قبل ما تجرّب تاني.",
  unexpected_response: "ما قدرناش نقرأ الرد بشكل آمن. إجاباتك اللي بعتها لسه موجودة هنا. جرّب تاني بعد شوية.",
  failure: "ما قدرناش نكمّل",
  wait: "تقدر تجرّب تاني بعد",
  seconds: "ثانية.",
  inconclusive: "مش قادرين نجهّز إرشادات موثوقة دلوقتي",
  inconclusiveHint: "ده مش قرار بخصوص طلبك. راجع إجاباتك، جرّب تاريخ تاني، أو ارجع بعد شوية. مش هنختار حالة قريبة بدل حالتك.",
  invalid: "في معلومات محتاجة مراجعة",
  invalidHint: "راجع الإجابات اللي تحت. تصحيحها بيمسح أول إجابة متأثرة وكل اللي بعدها.",
  invalidGeneral: "ما قدرناش نستخدم الطلب ده. راجع التاريخ وإجاباتك وجرّب تاني. لو المشكلة مستمرة، امسح الحالة أو ارجع بعد شوية.",
  contradictory: "في إجابات متعارضة مع بعض. راجعها، وما تختارش إجابة لمجرد إنك تكمّل.",
  correct: "صحّح الإجابات دي",
  correctDate: "صحّح التاريخ",
  configuration: "مش قادرين نكمّل بالسؤال ده",
  configurationHint: "الخدمة رجّعت سؤال مش هيسمح لنا نكمّل الحالة بشكل آمن. ما غيّرناش إجاباتك. راجعها، جرّب بعد شوية، أو امسح الحالة. مش هنخمّن السؤال اللي بعده.",
  planReady: "إرشادات تجهيزك",
  print: "اطبع الإرشادات",
  printHint: "الطباعة من متصفحك. النسخ المطبوعة أو المحفوظة ممكن تحتوي على معلومات شخصية؛ احتفظ بيها في مكان آمن.",
};
export function copy(locale: Locale): Copy { return locale === "ar" ? ar : en; }
